insert into vocabulary (type, value, description) values ('language_code', 'aar', 'Afar');
insert into vocabulary (type, value, description) values ('language_code', 'abk', 'Abkhazian');
insert into vocabulary (type, value, description) values ('language_code', 'ace', 'Achinese');
insert into vocabulary (type, value, description) values ('language_code', 'ach', 'Acoli');
insert into vocabulary (type, value, description) values ('language_code', 'ada', 'Adangme');
insert into vocabulary (type, value, description) values ('language_code', 'ady', 'Adyghe; Adygei');
insert into vocabulary (type, value, description) values ('language_code', 'afa', 'Afro-Asiatic languages');
insert into vocabulary (type, value, description) values ('language_code', 'afh', 'Afrihili');
insert into vocabulary (type, value, description) values ('language_code', 'afr', 'Afrikaans');
insert into vocabulary (type, value, description) values ('language_code', 'ain', 'Ainu');
insert into vocabulary (type, value, description) values ('language_code', 'aka', 'Akan');
insert into vocabulary (type, value, description) values ('language_code', 'akk', 'Akkadian');
insert into vocabulary (type, value, description) values ('language_code', 'alb', 'Albanian');
insert into vocabulary (type, value, description) values ('language_code', 'sqi', 'Albanian');
insert into vocabulary (type, value, description) values ('language_code', 'ale', 'Aleut');
insert into vocabulary (type, value, description) values ('language_code', 'alg', 'Algonquian languages');
insert into vocabulary (type, value, description) values ('language_code', 'alt', 'Southern Altai');
insert into vocabulary (type, value, description) values ('language_code', 'amh', 'Amharic');
insert into vocabulary (type, value, description) values ('language_code', 'ang', 'English, Old (ca.450-1100)');
insert into vocabulary (type, value, description) values ('language_code', 'anp', 'Angika');
insert into vocabulary (type, value, description) values ('language_code', 'apa', 'Apache languages');
insert into vocabulary (type, value, description) values ('language_code', 'ara', 'Arabic');
insert into vocabulary (type, value, description) values ('language_code', 'arc', 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)');
insert into vocabulary (type, value, description) values ('language_code', 'arg', 'Aragonese');
insert into vocabulary (type, value, description) values ('language_code', 'arm', 'Armenian');
insert into vocabulary (type, value, description) values ('language_code', 'hye', 'Armenian');
insert into vocabulary (type, value, description) values ('language_code', 'arn', 'Mapudungun; Mapuche');
insert into vocabulary (type, value, description) values ('language_code', 'arp', 'Arapaho');
insert into vocabulary (type, value, description) values ('language_code', 'art', 'Artificial languages');
insert into vocabulary (type, value, description) values ('language_code', 'arw', 'Arawak');
insert into vocabulary (type, value, description) values ('language_code', 'asm', 'Assamese');
insert into vocabulary (type, value, description) values ('language_code', 'ast', 'Asturian; Bable; Leonese; Asturleonese');
insert into vocabulary (type, value, description) values ('language_code', 'ath', 'Athapascan languages');
insert into vocabulary (type, value, description) values ('language_code', 'aus', 'Australian languages');
insert into vocabulary (type, value, description) values ('language_code', 'ava', 'Avaric');
insert into vocabulary (type, value, description) values ('language_code', 'ave', 'Avestan');
insert into vocabulary (type, value, description) values ('language_code', 'awa', 'Awadhi');
insert into vocabulary (type, value, description) values ('language_code', 'aym', 'Aymara');
insert into vocabulary (type, value, description) values ('language_code', 'aze', 'Azerbaijani');
insert into vocabulary (type, value, description) values ('language_code', 'bad', 'Banda languages');
insert into vocabulary (type, value, description) values ('language_code', 'bai', 'Bamileke languages');
insert into vocabulary (type, value, description) values ('language_code', 'bak', 'Bashkir');
insert into vocabulary (type, value, description) values ('language_code', 'bal', 'Baluchi');
insert into vocabulary (type, value, description) values ('language_code', 'bam', 'Bambara');
insert into vocabulary (type, value, description) values ('language_code', 'ban', 'Balinese');
insert into vocabulary (type, value, description) values ('language_code', 'baq', 'Basque');
insert into vocabulary (type, value, description) values ('language_code', 'eus', 'Basque');
insert into vocabulary (type, value, description) values ('language_code', 'bas', 'Basa');
insert into vocabulary (type, value, description) values ('language_code', 'bat', 'Baltic languages');
insert into vocabulary (type, value, description) values ('language_code', 'bej', 'Beja; Bedawiyet');
insert into vocabulary (type, value, description) values ('language_code', 'bel', 'Belarusian');
insert into vocabulary (type, value, description) values ('language_code', 'bem', 'Bemba');
insert into vocabulary (type, value, description) values ('language_code', 'ben', 'Bengali');
insert into vocabulary (type, value, description) values ('language_code', 'ber', 'Berber languages');
insert into vocabulary (type, value, description) values ('language_code', 'bho', 'Bhojpuri');
insert into vocabulary (type, value, description) values ('language_code', 'bih', 'Bihari languages');
insert into vocabulary (type, value, description) values ('language_code', 'bik', 'Bikol');
insert into vocabulary (type, value, description) values ('language_code', 'bin', 'Bini; Edo');
insert into vocabulary (type, value, description) values ('language_code', 'bis', 'Bislama');
insert into vocabulary (type, value, description) values ('language_code', 'bla', 'Siksika');
insert into vocabulary (type, value, description) values ('language_code', 'bnt', 'Bantu (Other)');
insert into vocabulary (type, value, description) values ('language_code', 'bos', 'Bosnian');
insert into vocabulary (type, value, description) values ('language_code', 'bra', 'Braj');
insert into vocabulary (type, value, description) values ('language_code', 'bre', 'Breton');
insert into vocabulary (type, value, description) values ('language_code', 'btk', 'Batak languages');
insert into vocabulary (type, value, description) values ('language_code', 'bua', 'Buriat');
insert into vocabulary (type, value, description) values ('language_code', 'bug', 'Buginese');
insert into vocabulary (type, value, description) values ('language_code', 'bul', 'Bulgarian');
insert into vocabulary (type, value, description) values ('language_code', 'bur', 'Burmese');
insert into vocabulary (type, value, description) values ('language_code', 'mya', 'Burmese');
insert into vocabulary (type, value, description) values ('language_code', 'byn', 'Blin; Bilin');
insert into vocabulary (type, value, description) values ('language_code', 'cad', 'Caddo');
insert into vocabulary (type, value, description) values ('language_code', 'cai', 'Central American Indian languages');
insert into vocabulary (type, value, description) values ('language_code', 'car', 'Galibi Carib');
insert into vocabulary (type, value, description) values ('language_code', 'cat', 'Catalan; Valencian');
insert into vocabulary (type, value, description) values ('language_code', 'cau', 'Caucasian languages');
insert into vocabulary (type, value, description) values ('language_code', 'ceb', 'Cebuano');
insert into vocabulary (type, value, description) values ('language_code', 'cel', 'Celtic languages');
insert into vocabulary (type, value, description) values ('language_code', 'cha', 'Chamorro');
insert into vocabulary (type, value, description) values ('language_code', 'chb', 'Chibcha');
insert into vocabulary (type, value, description) values ('language_code', 'che', 'Chechen');
insert into vocabulary (type, value, description) values ('language_code', 'chg', 'Chagatai');
insert into vocabulary (type, value, description) values ('language_code', 'chi', 'Chinese');
insert into vocabulary (type, value, description) values ('language_code', 'zho', 'Chinese');
insert into vocabulary (type, value, description) values ('language_code', 'chk', 'Chuukese');
insert into vocabulary (type, value, description) values ('language_code', 'chm', 'Mari');
insert into vocabulary (type, value, description) values ('language_code', 'chn', 'Chinook jargon');
insert into vocabulary (type, value, description) values ('language_code', 'cho', 'Choctaw');
insert into vocabulary (type, value, description) values ('language_code', 'chp', 'Chipewyan; Dene Suline');
insert into vocabulary (type, value, description) values ('language_code', 'chr', 'Cherokee');
insert into vocabulary (type, value, description) values ('language_code', 'chu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic');
insert into vocabulary (type, value, description) values ('language_code', 'chv', 'Chuvash');
insert into vocabulary (type, value, description) values ('language_code', 'chy', 'Cheyenne');
insert into vocabulary (type, value, description) values ('language_code', 'cmc', 'Chamic languages');
insert into vocabulary (type, value, description) values ('language_code', 'cop', 'Coptic');
insert into vocabulary (type, value, description) values ('language_code', 'cor', 'Cornish');
insert into vocabulary (type, value, description) values ('language_code', 'cos', 'Corsican');
insert into vocabulary (type, value, description) values ('language_code', 'cpe', 'Creoles and pidgins, English based');
insert into vocabulary (type, value, description) values ('language_code', 'cpf', 'Creoles and pidgins, French-based ');
insert into vocabulary (type, value, description) values ('language_code', 'cpp', 'Creoles and pidgins, Portuguese-based ');
insert into vocabulary (type, value, description) values ('language_code', 'cre', 'Cree');
insert into vocabulary (type, value, description) values ('language_code', 'crh', 'Crimean Tatar; Crimean Turkish');
insert into vocabulary (type, value, description) values ('language_code', 'crp', 'Creoles and pidgins ');
insert into vocabulary (type, value, description) values ('language_code', 'csb', 'Kashubian');
insert into vocabulary (type, value, description) values ('language_code', 'cus', 'Cushitic languages');
insert into vocabulary (type, value, description) values ('language_code', 'cze', 'Czech');
insert into vocabulary (type, value, description) values ('language_code', 'ces', 'Czech');
insert into vocabulary (type, value, description) values ('language_code', 'dak', 'Dakota');
insert into vocabulary (type, value, description) values ('language_code', 'dan', 'Danish');
insert into vocabulary (type, value, description) values ('language_code', 'dar', 'Dargwa');
insert into vocabulary (type, value, description) values ('language_code', 'day', 'Land Dayak languages');
insert into vocabulary (type, value, description) values ('language_code', 'del', 'Delaware');
insert into vocabulary (type, value, description) values ('language_code', 'den', 'Slave (Athapascan)');
insert into vocabulary (type, value, description) values ('language_code', 'dgr', 'Dogrib');
insert into vocabulary (type, value, description) values ('language_code', 'din', 'Dinka');
insert into vocabulary (type, value, description) values ('language_code', 'div', 'Divehi; Dhivehi; Maldivian');
insert into vocabulary (type, value, description) values ('language_code', 'doi', 'Dogri');
insert into vocabulary (type, value, description) values ('language_code', 'dra', 'Dravidian languages');
insert into vocabulary (type, value, description) values ('language_code', 'dsb', 'Lower Sorbian');
insert into vocabulary (type, value, description) values ('language_code', 'dua', 'Duala');
insert into vocabulary (type, value, description) values ('language_code', 'dum', 'Dutch, Middle (ca.1050-1350)');
insert into vocabulary (type, value, description) values ('language_code', 'dut', 'Dutch; Flemish');
insert into vocabulary (type, value, description) values ('language_code', 'nld', 'Dutch; Flemish');
insert into vocabulary (type, value, description) values ('language_code', 'dyu', 'Dyula');
insert into vocabulary (type, value, description) values ('language_code', 'dzo', 'Dzongkha');
insert into vocabulary (type, value, description) values ('language_code', 'efi', 'Efik');
insert into vocabulary (type, value, description) values ('language_code', 'egy', 'Egyptian (Ancient)');
insert into vocabulary (type, value, description) values ('language_code', 'eka', 'Ekajuk');
insert into vocabulary (type, value, description) values ('language_code', 'elx', 'Elamite');
insert into vocabulary (type, value, description) values ('language_code', 'eng', 'English');
insert into vocabulary (type, value, description) values ('language_code', 'enm', 'English, Middle (1100-1500)');
insert into vocabulary (type, value, description) values ('language_code', 'epo', 'Esperanto');
insert into vocabulary (type, value, description) values ('language_code', 'est', 'Estonian');
insert into vocabulary (type, value, description) values ('language_code', 'ewe', 'Ewe');
insert into vocabulary (type, value, description) values ('language_code', 'ewo', 'Ewondo');
insert into vocabulary (type, value, description) values ('language_code', 'fan', 'Fang');
insert into vocabulary (type, value, description) values ('language_code', 'fao', 'Faroese');
insert into vocabulary (type, value, description) values ('language_code', 'fat', 'Fanti');
insert into vocabulary (type, value, description) values ('language_code', 'fij', 'Fijian');
insert into vocabulary (type, value, description) values ('language_code', 'fil', 'Filipino; Pilipino');
insert into vocabulary (type, value, description) values ('language_code', 'fin', 'Finnish');
insert into vocabulary (type, value, description) values ('language_code', 'fiu', 'Finno-Ugrian languages');
insert into vocabulary (type, value, description) values ('language_code', 'fon', 'Fon');
insert into vocabulary (type, value, description) values ('language_code', 'fre', 'French');
insert into vocabulary (type, value, description) values ('language_code', 'fra', 'French');
insert into vocabulary (type, value, description) values ('language_code', 'frm', 'French, Middle (ca.1400-1600)');
insert into vocabulary (type, value, description) values ('language_code', 'fro', 'French, Old (842-ca.1400)');
insert into vocabulary (type, value, description) values ('language_code', 'frr', 'Northern Frisian');
insert into vocabulary (type, value, description) values ('language_code', 'frs', 'Eastern Frisian');
insert into vocabulary (type, value, description) values ('language_code', 'fry', 'Western Frisian');
insert into vocabulary (type, value, description) values ('language_code', 'ful', 'Fulah');
insert into vocabulary (type, value, description) values ('language_code', 'fur', 'Friulian');
insert into vocabulary (type, value, description) values ('language_code', 'gaa', 'Ga');
insert into vocabulary (type, value, description) values ('language_code', 'gay', 'Gayo');
insert into vocabulary (type, value, description) values ('language_code', 'gba', 'Gbaya');
insert into vocabulary (type, value, description) values ('language_code', 'gem', 'Germanic languages');
insert into vocabulary (type, value, description) values ('language_code', 'geo', 'Georgian');
insert into vocabulary (type, value, description) values ('language_code', 'kat', 'Georgian');
insert into vocabulary (type, value, description) values ('language_code', 'ger', 'German');
insert into vocabulary (type, value, description) values ('language_code', 'deu', 'German');
insert into vocabulary (type, value, description) values ('language_code', 'gez', 'Geez');
insert into vocabulary (type, value, description) values ('language_code', 'gil', 'Gilbertese');
insert into vocabulary (type, value, description) values ('language_code', 'gla', 'Gaelic; Scottish Gaelic');
insert into vocabulary (type, value, description) values ('language_code', 'gle', 'Irish');
insert into vocabulary (type, value, description) values ('language_code', 'glg', 'Galician');
insert into vocabulary (type, value, description) values ('language_code', 'glv', 'Manx');
insert into vocabulary (type, value, description) values ('language_code', 'gmh', 'German, Middle High (ca.1050-1500)');
insert into vocabulary (type, value, description) values ('language_code', 'goh', 'German, Old High (ca.750-1050)');
insert into vocabulary (type, value, description) values ('language_code', 'gon', 'Gondi');
insert into vocabulary (type, value, description) values ('language_code', 'gor', 'Gorontalo');
insert into vocabulary (type, value, description) values ('language_code', 'got', 'Gothic');
insert into vocabulary (type, value, description) values ('language_code', 'grb', 'Grebo');
insert into vocabulary (type, value, description) values ('language_code', 'grc', 'Greek, Ancient (to 1453)');
insert into vocabulary (type, value, description) values ('language_code', 'gre', 'Greek, Modern (1453-)');
insert into vocabulary (type, value, description) values ('language_code', 'ell', 'Greek, Modern (1453-)');
insert into vocabulary (type, value, description) values ('language_code', 'grn', 'Guarani');
insert into vocabulary (type, value, description) values ('language_code', 'gsw', 'Swiss German; Alemannic; Alsatian');
insert into vocabulary (type, value, description) values ('language_code', 'guj', 'Gujarati');
insert into vocabulary (type, value, description) values ('language_code', 'gwi', 'Gwich''in');
insert into vocabulary (type, value, description) values ('language_code', 'hai', 'Haida');
insert into vocabulary (type, value, description) values ('language_code', 'hat', 'Haitian; Haitian Creole');
insert into vocabulary (type, value, description) values ('language_code', 'hau', 'Hausa');
insert into vocabulary (type, value, description) values ('language_code', 'haw', 'Hawaiian');
insert into vocabulary (type, value, description) values ('language_code', 'heb', 'Hebrew');
insert into vocabulary (type, value, description) values ('language_code', 'her', 'Herero');
insert into vocabulary (type, value, description) values ('language_code', 'hil', 'Hiligaynon');
insert into vocabulary (type, value, description) values ('language_code', 'him', 'Himachali languages; Western Pahari languages');
insert into vocabulary (type, value, description) values ('language_code', 'hin', 'Hindi');
insert into vocabulary (type, value, description) values ('language_code', 'hit', 'Hittite');
insert into vocabulary (type, value, description) values ('language_code', 'hmn', 'Hmong; Mong');
insert into vocabulary (type, value, description) values ('language_code', 'hmo', 'Hiri Motu');
insert into vocabulary (type, value, description) values ('language_code', 'hrv', 'Croatian');
insert into vocabulary (type, value, description) values ('language_code', 'hsb', 'Upper Sorbian');
insert into vocabulary (type, value, description) values ('language_code', 'hun', 'Hungarian');
insert into vocabulary (type, value, description) values ('language_code', 'hup', 'Hupa');
insert into vocabulary (type, value, description) values ('language_code', 'iba', 'Iban');
insert into vocabulary (type, value, description) values ('language_code', 'ibo', 'Igbo');
insert into vocabulary (type, value, description) values ('language_code', 'ice', 'Icelandic');
insert into vocabulary (type, value, description) values ('language_code', 'isl', 'Icelandic');
insert into vocabulary (type, value, description) values ('language_code', 'ido', 'Ido');
insert into vocabulary (type, value, description) values ('language_code', 'iii', 'Sichuan Yi; Nuosu');
insert into vocabulary (type, value, description) values ('language_code', 'ijo', 'Ijo languages');
insert into vocabulary (type, value, description) values ('language_code', 'iku', 'Inuktitut');
insert into vocabulary (type, value, description) values ('language_code', 'ile', 'Interlingue; Occidental');
insert into vocabulary (type, value, description) values ('language_code', 'ilo', 'Iloko');
insert into vocabulary (type, value, description) values ('language_code', 'ina', 'Interlingua (International Auxiliary Language Association)');
insert into vocabulary (type, value, description) values ('language_code', 'inc', 'Indic languages');
insert into vocabulary (type, value, description) values ('language_code', 'ind', 'Indonesian');
insert into vocabulary (type, value, description) values ('language_code', 'ine', 'Indo-European languages');
insert into vocabulary (type, value, description) values ('language_code', 'inh', 'Ingush');
insert into vocabulary (type, value, description) values ('language_code', 'ipk', 'Inupiaq');
insert into vocabulary (type, value, description) values ('language_code', 'ira', 'Iranian languages');
insert into vocabulary (type, value, description) values ('language_code', 'iro', 'Iroquoian languages');
insert into vocabulary (type, value, description) values ('language_code', 'ita', 'Italian');
insert into vocabulary (type, value, description) values ('language_code', 'jav', 'Javanese');
insert into vocabulary (type, value, description) values ('language_code', 'jbo', 'Lojban');
insert into vocabulary (type, value, description) values ('language_code', 'jpn', 'Japanese');
insert into vocabulary (type, value, description) values ('language_code', 'jpr', 'Judeo-Persian');
insert into vocabulary (type, value, description) values ('language_code', 'jrb', 'Judeo-Arabic');
insert into vocabulary (type, value, description) values ('language_code', 'kaa', 'Kara-Kalpak');
insert into vocabulary (type, value, description) values ('language_code', 'kab', 'Kabyle');
insert into vocabulary (type, value, description) values ('language_code', 'kac', 'Kachin; Jingpho');
insert into vocabulary (type, value, description) values ('language_code', 'kal', 'Kalaallisut; Greenlandic');
insert into vocabulary (type, value, description) values ('language_code', 'kam', 'Kamba');
insert into vocabulary (type, value, description) values ('language_code', 'kan', 'Kannada');
insert into vocabulary (type, value, description) values ('language_code', 'kar', 'Karen languages');
insert into vocabulary (type, value, description) values ('language_code', 'kas', 'Kashmiri');
insert into vocabulary (type, value, description) values ('language_code', 'kau', 'Kanuri');
insert into vocabulary (type, value, description) values ('language_code', 'kaw', 'Kawi');
insert into vocabulary (type, value, description) values ('language_code', 'kaz', 'Kazakh');
insert into vocabulary (type, value, description) values ('language_code', 'kbd', 'Kabardian');
insert into vocabulary (type, value, description) values ('language_code', 'kha', 'Khasi');
insert into vocabulary (type, value, description) values ('language_code', 'khi', 'Khoisan languages');
insert into vocabulary (type, value, description) values ('language_code', 'khm', 'Central Khmer');
insert into vocabulary (type, value, description) values ('language_code', 'kho', 'Khotanese; Sakan');
insert into vocabulary (type, value, description) values ('language_code', 'kik', 'Kikuyu; Gikuyu');
insert into vocabulary (type, value, description) values ('language_code', 'kin', 'Kinyarwanda');
insert into vocabulary (type, value, description) values ('language_code', 'kir', 'Kirghiz; Kyrgyz');
insert into vocabulary (type, value, description) values ('language_code', 'kmb', 'Kimbundu');
insert into vocabulary (type, value, description) values ('language_code', 'kok', 'Konkani');
insert into vocabulary (type, value, description) values ('language_code', 'kom', 'Komi');
insert into vocabulary (type, value, description) values ('language_code', 'kon', 'Kongo');
insert into vocabulary (type, value, description) values ('language_code', 'kor', 'Korean');
insert into vocabulary (type, value, description) values ('language_code', 'kos', 'Kosraean');
insert into vocabulary (type, value, description) values ('language_code', 'kpe', 'Kpelle');
insert into vocabulary (type, value, description) values ('language_code', 'krc', 'Karachay-Balkar');
insert into vocabulary (type, value, description) values ('language_code', 'krl', 'Karelian');
insert into vocabulary (type, value, description) values ('language_code', 'kro', 'Kru languages');
insert into vocabulary (type, value, description) values ('language_code', 'kru', 'Kurukh');
insert into vocabulary (type, value, description) values ('language_code', 'kua', 'Kuanyama; Kwanyama');
insert into vocabulary (type, value, description) values ('language_code', 'kum', 'Kumyk');
insert into vocabulary (type, value, description) values ('language_code', 'kur', 'Kurdish');
insert into vocabulary (type, value, description) values ('language_code', 'kut', 'Kutenai');
insert into vocabulary (type, value, description) values ('language_code', 'lad', 'Ladino');
insert into vocabulary (type, value, description) values ('language_code', 'lah', 'Lahnda');
insert into vocabulary (type, value, description) values ('language_code', 'lam', 'Lamba');
insert into vocabulary (type, value, description) values ('language_code', 'lao', 'Lao');
insert into vocabulary (type, value, description) values ('language_code', 'lat', 'Latin');
insert into vocabulary (type, value, description) values ('language_code', 'lav', 'Latvian');
insert into vocabulary (type, value, description) values ('language_code', 'lez', 'Lezghian');
insert into vocabulary (type, value, description) values ('language_code', 'lim', 'Limburgan; Limburger; Limburgish');
insert into vocabulary (type, value, description) values ('language_code', 'lin', 'Lingala');
insert into vocabulary (type, value, description) values ('language_code', 'lit', 'Lithuanian');
insert into vocabulary (type, value, description) values ('language_code', 'lol', 'Mongo');
insert into vocabulary (type, value, description) values ('language_code', 'loz', 'Lozi');
insert into vocabulary (type, value, description) values ('language_code', 'ltz', 'Luxembourgish; Letzeburgesch');
insert into vocabulary (type, value, description) values ('language_code', 'lua', 'Luba-Lulua');
insert into vocabulary (type, value, description) values ('language_code', 'lub', 'Luba-Katanga');
insert into vocabulary (type, value, description) values ('language_code', 'lug', 'Ganda');
insert into vocabulary (type, value, description) values ('language_code', 'lui', 'Luiseno');
insert into vocabulary (type, value, description) values ('language_code', 'lun', 'Lunda');
insert into vocabulary (type, value, description) values ('language_code', 'luo', 'Luo (Kenya and Tanzania)');
insert into vocabulary (type, value, description) values ('language_code', 'lus', 'Lushai');
insert into vocabulary (type, value, description) values ('language_code', 'mac', 'Macedonian');
insert into vocabulary (type, value, description) values ('language_code', 'mkd', 'Macedonian');
insert into vocabulary (type, value, description) values ('language_code', 'mad', 'Madurese');
insert into vocabulary (type, value, description) values ('language_code', 'mag', 'Magahi');
insert into vocabulary (type, value, description) values ('language_code', 'mah', 'Marshallese');
insert into vocabulary (type, value, description) values ('language_code', 'mai', 'Maithili');
insert into vocabulary (type, value, description) values ('language_code', 'mak', 'Makasar');
insert into vocabulary (type, value, description) values ('language_code', 'mal', 'Malayalam');
insert into vocabulary (type, value, description) values ('language_code', 'man', 'Mandingo');
insert into vocabulary (type, value, description) values ('language_code', 'mao', 'Maori');
insert into vocabulary (type, value, description) values ('language_code', 'mri', 'Maori');
insert into vocabulary (type, value, description) values ('language_code', 'map', 'Austronesian languages');
insert into vocabulary (type, value, description) values ('language_code', 'mar', 'Marathi');
insert into vocabulary (type, value, description) values ('language_code', 'mas', 'Masai');
insert into vocabulary (type, value, description) values ('language_code', 'may', 'Malay');
insert into vocabulary (type, value, description) values ('language_code', 'msa', 'Malay');
insert into vocabulary (type, value, description) values ('language_code', 'mdf', 'Moksha');
insert into vocabulary (type, value, description) values ('language_code', 'mdr', 'Mandar');
insert into vocabulary (type, value, description) values ('language_code', 'men', 'Mende');
insert into vocabulary (type, value, description) values ('language_code', 'mga', 'Irish, Middle (900-1200)');
insert into vocabulary (type, value, description) values ('language_code', 'mic', 'Mi''kmaq; Micmac');
insert into vocabulary (type, value, description) values ('language_code', 'min', 'Minangkabau');
insert into vocabulary (type, value, description) values ('language_code', 'mis', 'Uncoded languages');
insert into vocabulary (type, value, description) values ('language_code', 'mkh', 'Mon-Khmer languages');
insert into vocabulary (type, value, description) values ('language_code', 'mlg', 'Malagasy');
insert into vocabulary (type, value, description) values ('language_code', 'mlt', 'Maltese');
insert into vocabulary (type, value, description) values ('language_code', 'mnc', 'Manchu');
insert into vocabulary (type, value, description) values ('language_code', 'mni', 'Manipuri');
insert into vocabulary (type, value, description) values ('language_code', 'mno', 'Manobo languages');
insert into vocabulary (type, value, description) values ('language_code', 'moh', 'Mohawk');
insert into vocabulary (type, value, description) values ('language_code', 'mon', 'Mongolian');
insert into vocabulary (type, value, description) values ('language_code', 'mos', 'Mossi');
insert into vocabulary (type, value, description) values ('language_code', 'mul', 'Multiple languages');
insert into vocabulary (type, value, description) values ('language_code', 'mun', 'Munda languages');
insert into vocabulary (type, value, description) values ('language_code', 'mus', 'Creek');
insert into vocabulary (type, value, description) values ('language_code', 'mwl', 'Mirandese');
insert into vocabulary (type, value, description) values ('language_code', 'mwr', 'Marwari');
insert into vocabulary (type, value, description) values ('language_code', 'myn', 'Mayan languages');
insert into vocabulary (type, value, description) values ('language_code', 'myv', 'Erzya');
insert into vocabulary (type, value, description) values ('language_code', 'nah', 'Nahuatl languages');
insert into vocabulary (type, value, description) values ('language_code', 'nai', 'North American Indian languages');
insert into vocabulary (type, value, description) values ('language_code', 'nap', 'Neapolitan');
insert into vocabulary (type, value, description) values ('language_code', 'nau', 'Nauru');
insert into vocabulary (type, value, description) values ('language_code', 'nav', 'Navajo; Navaho');
insert into vocabulary (type, value, description) values ('language_code', 'nbl', 'Ndebele, South; South Ndebele');
insert into vocabulary (type, value, description) values ('language_code', 'nde', 'Ndebele, North; North Ndebele');
insert into vocabulary (type, value, description) values ('language_code', 'ndo', 'Ndonga');
insert into vocabulary (type, value, description) values ('language_code', 'nds', 'Low German; Low Saxon; German, Low; Saxon, Low');
insert into vocabulary (type, value, description) values ('language_code', 'nep', 'Nepali');
insert into vocabulary (type, value, description) values ('language_code', 'new', 'Nepal Bhasa; Newari');
insert into vocabulary (type, value, description) values ('language_code', 'nia', 'Nias');
insert into vocabulary (type, value, description) values ('language_code', 'nic', 'Niger-Kordofanian languages');
insert into vocabulary (type, value, description) values ('language_code', 'niu', 'Niuean');
insert into vocabulary (type, value, description) values ('language_code', 'nno', 'Norwegian Nynorsk; Nynorsk, Norwegian');
insert into vocabulary (type, value, description) values ('language_code', 'nob', 'Bokmål, Norwegian; Norwegian Bokmål');
insert into vocabulary (type, value, description) values ('language_code', 'nog', 'Nogai');
insert into vocabulary (type, value, description) values ('language_code', 'non', 'Norse, Old');
insert into vocabulary (type, value, description) values ('language_code', 'nor', 'Norwegian');
insert into vocabulary (type, value, description) values ('language_code', 'nqo', 'N''Ko');
insert into vocabulary (type, value, description) values ('language_code', 'nso', 'Pedi; Sepedi; Northern Sotho');
insert into vocabulary (type, value, description) values ('language_code', 'nub', 'Nubian languages');
insert into vocabulary (type, value, description) values ('language_code', 'nwc', 'Classical Newari; Old Newari; Classical Nepal Bhasa');
insert into vocabulary (type, value, description) values ('language_code', 'nya', 'Chichewa; Chewa; Nyanja');
insert into vocabulary (type, value, description) values ('language_code', 'nym', 'Nyamwezi');
insert into vocabulary (type, value, description) values ('language_code', 'nyn', 'Nyankole');
insert into vocabulary (type, value, description) values ('language_code', 'nyo', 'Nyoro');
insert into vocabulary (type, value, description) values ('language_code', 'nzi', 'Nzima');
insert into vocabulary (type, value, description) values ('language_code', 'oci', 'Occitan (post 1500); Provençal');
insert into vocabulary (type, value, description) values ('language_code', 'oji', 'Ojibwa');
insert into vocabulary (type, value, description) values ('language_code', 'ori', 'Oriya');
insert into vocabulary (type, value, description) values ('language_code', 'orm', 'Oromo');
insert into vocabulary (type, value, description) values ('language_code', 'osa', 'Osage');
insert into vocabulary (type, value, description) values ('language_code', 'oss', 'Ossetian; Ossetic');
insert into vocabulary (type, value, description) values ('language_code', 'ota', 'Turkish, Ottoman (1500-1928)');
insert into vocabulary (type, value, description) values ('language_code', 'oto', 'Otomian languages');
insert into vocabulary (type, value, description) values ('language_code', 'paa', 'Papuan languages');
insert into vocabulary (type, value, description) values ('language_code', 'pag', 'Pangasinan');
insert into vocabulary (type, value, description) values ('language_code', 'pal', 'Pahlavi');
insert into vocabulary (type, value, description) values ('language_code', 'pam', 'Pampanga; Kapampangan');
insert into vocabulary (type, value, description) values ('language_code', 'pan', 'Panjabi; Punjabi');
insert into vocabulary (type, value, description) values ('language_code', 'pap', 'Papiamento');
insert into vocabulary (type, value, description) values ('language_code', 'pau', 'Palauan');
insert into vocabulary (type, value, description) values ('language_code', 'peo', 'Persian, Old (ca.600-400 B.C.)');
insert into vocabulary (type, value, description) values ('language_code', 'per', 'Persian');
insert into vocabulary (type, value, description) values ('language_code', 'fas', 'Persian');
insert into vocabulary (type, value, description) values ('language_code', 'phi', 'Philippine languages');
insert into vocabulary (type, value, description) values ('language_code', 'phn', 'Phoenician');
insert into vocabulary (type, value, description) values ('language_code', 'pli', 'Pali');
insert into vocabulary (type, value, description) values ('language_code', 'pol', 'Polish');
insert into vocabulary (type, value, description) values ('language_code', 'pon', 'Pohnpeian');
insert into vocabulary (type, value, description) values ('language_code', 'por', 'Portuguese');
insert into vocabulary (type, value, description) values ('language_code', 'pra', 'Prakrit languages');
insert into vocabulary (type, value, description) values ('language_code', 'pro', 'Provençal, Old (to 1500)');
insert into vocabulary (type, value, description) values ('language_code', 'pus', 'Pushto; Pashto');
insert into vocabulary (type, value, description) values ('language_code', 'qaa-qtz', 'Reserved for local use');
insert into vocabulary (type, value, description) values ('language_code', 'que', 'Quechua');
insert into vocabulary (type, value, description) values ('language_code', 'raj', 'Rajasthani');
insert into vocabulary (type, value, description) values ('language_code', 'rap', 'Rapanui');
insert into vocabulary (type, value, description) values ('language_code', 'rar', 'Rarotongan; Cook Islands Maori');
insert into vocabulary (type, value, description) values ('language_code', 'roa', 'Romance languages');
insert into vocabulary (type, value, description) values ('language_code', 'roh', 'Romansh');
insert into vocabulary (type, value, description) values ('language_code', 'rom', 'Romany');
insert into vocabulary (type, value, description) values ('language_code', 'rum', 'Romanian; Moldavian; Moldovan');
insert into vocabulary (type, value, description) values ('language_code', 'ron', 'Romanian; Moldavian; Moldovan');
insert into vocabulary (type, value, description) values ('language_code', 'run', 'Rundi');
insert into vocabulary (type, value, description) values ('language_code', 'rup', 'Aromanian; Arumanian; Macedo-Romanian');
insert into vocabulary (type, value, description) values ('language_code', 'rus', 'Russian');
insert into vocabulary (type, value, description) values ('language_code', 'sad', 'Sandawe');
insert into vocabulary (type, value, description) values ('language_code', 'sag', 'Sango');
insert into vocabulary (type, value, description) values ('language_code', 'sah', 'Yakut');
insert into vocabulary (type, value, description) values ('language_code', 'sai', 'South American Indian (Other)');
insert into vocabulary (type, value, description) values ('language_code', 'sal', 'Salishan languages');
insert into vocabulary (type, value, description) values ('language_code', 'sam', 'Samaritan Aramaic');
insert into vocabulary (type, value, description) values ('language_code', 'san', 'Sanskrit');
insert into vocabulary (type, value, description) values ('language_code', 'sas', 'Sasak');
insert into vocabulary (type, value, description) values ('language_code', 'sat', 'Santali');
insert into vocabulary (type, value, description) values ('language_code', 'scn', 'Sicilian');
insert into vocabulary (type, value, description) values ('language_code', 'sco', 'Scots');
insert into vocabulary (type, value, description) values ('language_code', 'sel', 'Selkup');
insert into vocabulary (type, value, description) values ('language_code', 'sem', 'Semitic languages');
insert into vocabulary (type, value, description) values ('language_code', 'sga', 'Irish, Old (to 900)');
insert into vocabulary (type, value, description) values ('language_code', 'sgn', 'Sign Languages');
insert into vocabulary (type, value, description) values ('language_code', 'shn', 'Shan');
insert into vocabulary (type, value, description) values ('language_code', 'sid', 'Sidamo');
insert into vocabulary (type, value, description) values ('language_code', 'sin', 'Sinhala; Sinhalese');
insert into vocabulary (type, value, description) values ('language_code', 'sio', 'Siouan languages');
insert into vocabulary (type, value, description) values ('language_code', 'sit', 'Sino-Tibetan languages');
insert into vocabulary (type, value, description) values ('language_code', 'sla', 'Slavic languages');
insert into vocabulary (type, value, description) values ('language_code', 'slo', 'Slovak');
insert into vocabulary (type, value, description) values ('language_code', 'slk', 'Slovak');
insert into vocabulary (type, value, description) values ('language_code', 'slv', 'Slovenian');
insert into vocabulary (type, value, description) values ('language_code', 'sma', 'Southern Sami');
insert into vocabulary (type, value, description) values ('language_code', 'sme', 'Northern Sami');
insert into vocabulary (type, value, description) values ('language_code', 'smi', 'Sami languages');
insert into vocabulary (type, value, description) values ('language_code', 'smj', 'Lule Sami');
insert into vocabulary (type, value, description) values ('language_code', 'smn', 'Inari Sami');
insert into vocabulary (type, value, description) values ('language_code', 'smo', 'Samoan');
insert into vocabulary (type, value, description) values ('language_code', 'sms', 'Skolt Sami');
insert into vocabulary (type, value, description) values ('language_code', 'sna', 'Shona');
insert into vocabulary (type, value, description) values ('language_code', 'snd', 'Sindhi');
insert into vocabulary (type, value, description) values ('language_code', 'snk', 'Soninke');
insert into vocabulary (type, value, description) values ('language_code', 'sog', 'Sogdian');
insert into vocabulary (type, value, description) values ('language_code', 'som', 'Somali');
insert into vocabulary (type, value, description) values ('language_code', 'son', 'Songhai languages');
insert into vocabulary (type, value, description) values ('language_code', 'sot', 'Sotho, Southern');
insert into vocabulary (type, value, description) values ('language_code', 'spa', 'Spanish; Castilian');
insert into vocabulary (type, value, description) values ('language_code', 'srd', 'Sardinian');
insert into vocabulary (type, value, description) values ('language_code', 'srn', 'Sranan Tongo');
insert into vocabulary (type, value, description) values ('language_code', 'srp', 'Serbian');
insert into vocabulary (type, value, description) values ('language_code', 'srr', 'Serer');
insert into vocabulary (type, value, description) values ('language_code', 'ssa', 'Nilo-Saharan languages');
insert into vocabulary (type, value, description) values ('language_code', 'ssw', 'Swati');
insert into vocabulary (type, value, description) values ('language_code', 'suk', 'Sukuma');
insert into vocabulary (type, value, description) values ('language_code', 'sun', 'Sundanese');
insert into vocabulary (type, value, description) values ('language_code', 'sus', 'Susu');
insert into vocabulary (type, value, description) values ('language_code', 'sux', 'Sumerian');
insert into vocabulary (type, value, description) values ('language_code', 'swa', 'Swahili');
insert into vocabulary (type, value, description) values ('language_code', 'swe', 'Swedish');
insert into vocabulary (type, value, description) values ('language_code', 'syc', 'Classical Syriac');
insert into vocabulary (type, value, description) values ('language_code', 'syr', 'Syriac');
insert into vocabulary (type, value, description) values ('language_code', 'tah', 'Tahitian');
insert into vocabulary (type, value, description) values ('language_code', 'tai', 'Tai languages');
insert into vocabulary (type, value, description) values ('language_code', 'tam', 'Tamil');
insert into vocabulary (type, value, description) values ('language_code', 'tat', 'Tatar');
insert into vocabulary (type, value, description) values ('language_code', 'tel', 'Telugu');
insert into vocabulary (type, value, description) values ('language_code', 'tem', 'Timne');
insert into vocabulary (type, value, description) values ('language_code', 'ter', 'Tereno');
insert into vocabulary (type, value, description) values ('language_code', 'tet', 'Tetum');
insert into vocabulary (type, value, description) values ('language_code', 'tgk', 'Tajik');
insert into vocabulary (type, value, description) values ('language_code', 'tgl', 'Tagalog');
insert into vocabulary (type, value, description) values ('language_code', 'tha', 'Thai');
insert into vocabulary (type, value, description) values ('language_code', 'tib', 'Tibetan');
insert into vocabulary (type, value, description) values ('language_code', 'bod', 'Tibetan');
insert into vocabulary (type, value, description) values ('language_code', 'tig', 'Tigre');
insert into vocabulary (type, value, description) values ('language_code', 'tir', 'Tigrinya');
insert into vocabulary (type, value, description) values ('language_code', 'tiv', 'Tiv');
insert into vocabulary (type, value, description) values ('language_code', 'tkl', 'Tokelau');
insert into vocabulary (type, value, description) values ('language_code', 'tlh', 'Klingon; tlhIngan-Hol');
insert into vocabulary (type, value, description) values ('language_code', 'tli', 'Tlingit');
insert into vocabulary (type, value, description) values ('language_code', 'tmh', 'Tamashek');
insert into vocabulary (type, value, description) values ('language_code', 'tog', 'Tonga (Nyasa)');
insert into vocabulary (type, value, description) values ('language_code', 'ton', 'Tonga (Tonga Islands)');
insert into vocabulary (type, value, description) values ('language_code', 'tpi', 'Tok Pisin');
insert into vocabulary (type, value, description) values ('language_code', 'tsi', 'Tsimshian');
insert into vocabulary (type, value, description) values ('language_code', 'tsn', 'Tswana');
insert into vocabulary (type, value, description) values ('language_code', 'tso', 'Tsonga');
insert into vocabulary (type, value, description) values ('language_code', 'tuk', 'Turkmen');
insert into vocabulary (type, value, description) values ('language_code', 'tum', 'Tumbuka');
insert into vocabulary (type, value, description) values ('language_code', 'tup', 'Tupi languages');
insert into vocabulary (type, value, description) values ('language_code', 'tur', 'Turkish');
insert into vocabulary (type, value, description) values ('language_code', 'tut', 'Altaic languages');
insert into vocabulary (type, value, description) values ('language_code', 'tvl', 'Tuvalu');
insert into vocabulary (type, value, description) values ('language_code', 'twi', 'Twi');
insert into vocabulary (type, value, description) values ('language_code', 'tyv', 'Tuvinian');
insert into vocabulary (type, value, description) values ('language_code', 'udm', 'Udmurt');
insert into vocabulary (type, value, description) values ('language_code', 'uga', 'Ugaritic');
insert into vocabulary (type, value, description) values ('language_code', 'uig', 'Uighur; Uyghur');
insert into vocabulary (type, value, description) values ('language_code', 'ukr', 'Ukrainian');
insert into vocabulary (type, value, description) values ('language_code', 'umb', 'Umbundu');
insert into vocabulary (type, value, description) values ('language_code', 'und', 'Undetermined');
insert into vocabulary (type, value, description) values ('language_code', 'urd', 'Urdu');
insert into vocabulary (type, value, description) values ('language_code', 'uzb', 'Uzbek');
insert into vocabulary (type, value, description) values ('language_code', 'vai', 'Vai');
insert into vocabulary (type, value, description) values ('language_code', 'ven', 'Venda');
insert into vocabulary (type, value, description) values ('language_code', 'vie', 'Vietnamese');
insert into vocabulary (type, value, description) values ('language_code', 'vol', 'Volapük');
insert into vocabulary (type, value, description) values ('language_code', 'vot', 'Votic');
insert into vocabulary (type, value, description) values ('language_code', 'wak', 'Wakashan languages');
insert into vocabulary (type, value, description) values ('language_code', 'wal', 'Walamo');
insert into vocabulary (type, value, description) values ('language_code', 'war', 'Waray');
insert into vocabulary (type, value, description) values ('language_code', 'was', 'Washo');
insert into vocabulary (type, value, description) values ('language_code', 'wel', 'Welsh');
insert into vocabulary (type, value, description) values ('language_code', 'cym', 'Welsh');
insert into vocabulary (type, value, description) values ('language_code', 'wen', 'Sorbian languages');
insert into vocabulary (type, value, description) values ('language_code', 'wln', 'Walloon');
insert into vocabulary (type, value, description) values ('language_code', 'wol', 'Wolof');
insert into vocabulary (type, value, description) values ('language_code', 'xal', 'Kalmyk; Oirat');
insert into vocabulary (type, value, description) values ('language_code', 'xho', 'Xhosa');
insert into vocabulary (type, value, description) values ('language_code', 'yao', 'Yao');
insert into vocabulary (type, value, description) values ('language_code', 'yap', 'Yapese');
insert into vocabulary (type, value, description) values ('language_code', 'yid', 'Yiddish');
insert into vocabulary (type, value, description) values ('language_code', 'yor', 'Yoruba');
insert into vocabulary (type, value, description) values ('language_code', 'ypk', 'Yupik languages');
insert into vocabulary (type, value, description) values ('language_code', 'zap', 'Zapotec');
insert into vocabulary (type, value, description) values ('language_code', 'zbl', 'Blissymbols; Blissymbolics; Bliss');
insert into vocabulary (type, value, description) values ('language_code', 'zen', 'Zenaga');
insert into vocabulary (type, value, description) values ('language_code', 'zgh', 'Standard Moroccan Tamazight');
insert into vocabulary (type, value, description) values ('language_code', 'zha', 'Zhuang; Chuang');
insert into vocabulary (type, value, description) values ('language_code', 'znd', 'Zande languages');
insert into vocabulary (type, value, description) values ('language_code', 'zul', 'Zulu');
insert into vocabulary (type, value, description) values ('language_code', 'zun', 'Zuni');
insert into vocabulary (type, value, description) values ('language_code', 'zxx', 'No linguistic content; Not applicable');
insert into vocabulary (type, value, description) values ('language_code', 'zza', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki');
