insert into vocabulary (type, value, description) values ('script_code', 'Adlm', 'Adlam');
insert into vocabulary (type, value, description) values ('script_code', 'Afak', 'Afaka');
insert into vocabulary (type, value, description) values ('script_code', 'Aghb', 'Caucasian Albanian');
insert into vocabulary (type, value, description) values ('script_code', 'Ahom', 'Ahom, Tai Ahom');
insert into vocabulary (type, value, description) values ('script_code', 'Arab', 'Arabic');
insert into vocabulary (type, value, description) values ('script_code', 'Aran', 'Arabic (Nastaliq variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Armi', 'Imperial Aramaic');
insert into vocabulary (type, value, description) values ('script_code', 'Armn', 'Armenian');
insert into vocabulary (type, value, description) values ('script_code', 'Avst', 'Avestan');
insert into vocabulary (type, value, description) values ('script_code', 'Bali', 'Balinese');
insert into vocabulary (type, value, description) values ('script_code', 'Bamu', 'Bamum');
insert into vocabulary (type, value, description) values ('script_code', 'Bass', 'Bassa Vah');
insert into vocabulary (type, value, description) values ('script_code', 'Batk', 'Batak');
insert into vocabulary (type, value, description) values ('script_code', 'Beng', 'Bengali');
insert into vocabulary (type, value, description) values ('script_code', 'Bhks', 'Bhaiksuki');
insert into vocabulary (type, value, description) values ('script_code', 'Blis', 'Blissymbols');
insert into vocabulary (type, value, description) values ('script_code', 'Bopo', 'Bopomofo');
insert into vocabulary (type, value, description) values ('script_code', 'Brah', 'Brahmi');
insert into vocabulary (type, value, description) values ('script_code', 'Brai', 'Braille');
insert into vocabulary (type, value, description) values ('script_code', 'Bugi', 'Buginese');
insert into vocabulary (type, value, description) values ('script_code', 'Buhd', 'Buhid');
insert into vocabulary (type, value, description) values ('script_code', 'Cakm', 'Chakma');
insert into vocabulary (type, value, description) values ('script_code', 'Cans', 'Unified Canadian Aboriginal Syllabics');
insert into vocabulary (type, value, description) values ('script_code', 'Cari', 'Carian');
insert into vocabulary (type, value, description) values ('script_code', 'Cham', 'Cham');
insert into vocabulary (type, value, description) values ('script_code', 'Cher', 'Cherokee');
insert into vocabulary (type, value, description) values ('script_code', 'Cirt', 'Cirth');
insert into vocabulary (type, value, description) values ('script_code', 'Copt', 'Coptic');
insert into vocabulary (type, value, description) values ('script_code', 'Cprt', 'Cypriot');
insert into vocabulary (type, value, description) values ('script_code', 'Cyrl', 'Cyrillic');
insert into vocabulary (type, value, description) values ('script_code', 'Cyrs', 'Cyrillic (Old Church Slavonic variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Deva', 'Devanagari (Nagari)');
insert into vocabulary (type, value, description) values ('script_code', 'Dsrt', 'Deseret (Mormon)');
insert into vocabulary (type, value, description) values ('script_code', 'Dupl', 'Duployan shorthand, Duployan stenography');
insert into vocabulary (type, value, description) values ('script_code', 'Egyd', 'Egyptian demotic');
insert into vocabulary (type, value, description) values ('script_code', 'Egyh', 'Egyptian hieratic');
insert into vocabulary (type, value, description) values ('script_code', 'Egyp', 'Egyptian hieroglyphs');
insert into vocabulary (type, value, description) values ('script_code', 'Elba', 'Elbasan');
insert into vocabulary (type, value, description) values ('script_code', 'Ethi', 'Ethiopic (Geʻez)');
insert into vocabulary (type, value, description) values ('script_code', 'Geok', 'Khutsuri (Asomtavruli and Nuskhuri)');
insert into vocabulary (type, value, description) values ('script_code', 'Geor', 'Georgian (Mkhedruli)');
insert into vocabulary (type, value, description) values ('script_code', 'Glag', 'Glagolitic');
insert into vocabulary (type, value, description) values ('script_code', 'Goth', 'Gothic');
insert into vocabulary (type, value, description) values ('script_code', 'Gran', 'Grantha');
insert into vocabulary (type, value, description) values ('script_code', 'Grek', 'Greek');
insert into vocabulary (type, value, description) values ('script_code', 'Gujr', 'Gujarati');
insert into vocabulary (type, value, description) values ('script_code', 'Guru', 'Gurmukhi');
insert into vocabulary (type, value, description) values ('script_code', 'Hang', 'Hangul (Hangŭl, Hangeul)');
insert into vocabulary (type, value, description) values ('script_code', 'Hani', 'Han (Hanzi, Kanji, Hanja)');
insert into vocabulary (type, value, description) values ('script_code', 'Hano', 'Hanunoo (Hanunóo)');
insert into vocabulary (type, value, description) values ('script_code', 'Hans', 'Han (Simplified variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Hant', 'Han (Traditional variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Hatr', 'Hatran');
insert into vocabulary (type, value, description) values ('script_code', 'Hebr', 'Hebrew');
insert into vocabulary (type, value, description) values ('script_code', 'Hira', 'Hiragana');
insert into vocabulary (type, value, description) values ('script_code', 'Hluw', 'Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)');
insert into vocabulary (type, value, description) values ('script_code', 'Hmng', 'Pahawh Hmong');
insert into vocabulary (type, value, description) values ('script_code', 'Hrkt', 'Japanese syllabaries (alias for Hiragana + Katakana)');
insert into vocabulary (type, value, description) values ('script_code', 'Hung', 'Old Hungarian (Hungarian Runic)');
insert into vocabulary (type, value, description) values ('script_code', 'Inds', 'Indus (Harappan)');
insert into vocabulary (type, value, description) values ('script_code', 'Ital', 'Old Italic (Etruscan, Oscan, etc.)');
insert into vocabulary (type, value, description) values ('script_code', 'Java', 'Javanese');
insert into vocabulary (type, value, description) values ('script_code', 'Jpan', 'Japanese (alias for Han + Hiragana + Katakana)');
insert into vocabulary (type, value, description) values ('script_code', 'Jurc', 'Jurchen');
insert into vocabulary (type, value, description) values ('script_code', 'Kali', 'Kayah Li');
insert into vocabulary (type, value, description) values ('script_code', 'Kana', 'Katakana');
insert into vocabulary (type, value, description) values ('script_code', 'Khar', 'Kharoshthi');
insert into vocabulary (type, value, description) values ('script_code', 'Khmr', 'Khmer');
insert into vocabulary (type, value, description) values ('script_code', 'Khoj', 'Khojki');
insert into vocabulary (type, value, description) values ('script_code', 'Kitl', 'Khitan large script');
insert into vocabulary (type, value, description) values ('script_code', 'Kits', 'Khitan small script');
insert into vocabulary (type, value, description) values ('script_code', 'Knda', 'Kannada');
insert into vocabulary (type, value, description) values ('script_code', 'Kore', 'Korean (alias for Hangul + Han)');
insert into vocabulary (type, value, description) values ('script_code', 'Kpel', 'Kpelle');
insert into vocabulary (type, value, description) values ('script_code', 'Kthi', 'Kaithi');
insert into vocabulary (type, value, description) values ('script_code', 'Lana', 'Tai Tham (Lanna)');
insert into vocabulary (type, value, description) values ('script_code', 'Laoo', 'Lao');
insert into vocabulary (type, value, description) values ('script_code', 'Latf', 'Latin (Fraktur variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Latg', 'Latin (Gaelic variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Latn', 'Latin');
insert into vocabulary (type, value, description) values ('script_code', 'Leke', 'Leke');
insert into vocabulary (type, value, description) values ('script_code', 'Lepc', 'Lepcha (Róng)');
insert into vocabulary (type, value, description) values ('script_code', 'Limb', 'Limbu');
insert into vocabulary (type, value, description) values ('script_code', 'Lina', 'Linear A');
insert into vocabulary (type, value, description) values ('script_code', 'Linb', 'Linear B');
insert into vocabulary (type, value, description) values ('script_code', 'Lisu', 'Lisu (Fraser)');
insert into vocabulary (type, value, description) values ('script_code', 'Loma', 'Loma');
insert into vocabulary (type, value, description) values ('script_code', 'Lyci', 'Lycian');
insert into vocabulary (type, value, description) values ('script_code', 'Lydi', 'Lydian');
insert into vocabulary (type, value, description) values ('script_code', 'Mahj', 'Mahajani');
insert into vocabulary (type, value, description) values ('script_code', 'Mand', 'Mandaic, Mandaean');
insert into vocabulary (type, value, description) values ('script_code', 'Mani', 'Manichaean');
insert into vocabulary (type, value, description) values ('script_code', 'Marc', 'Marchen');
insert into vocabulary (type, value, description) values ('script_code', 'Maya', 'Mayan hieroglyphs');
insert into vocabulary (type, value, description) values ('script_code', 'Mend', 'Mende Kikakui');
insert into vocabulary (type, value, description) values ('script_code', 'Merc', 'Meroitic Cursive');
insert into vocabulary (type, value, description) values ('script_code', 'Mero', 'Meroitic Hieroglyphs');
insert into vocabulary (type, value, description) values ('script_code', 'Mlym', 'Malayalam');
insert into vocabulary (type, value, description) values ('script_code', 'Modi', 'Modi, Moḍī');
insert into vocabulary (type, value, description) values ('script_code', 'Mong', 'Mongolian');
insert into vocabulary (type, value, description) values ('script_code', 'Moon', 'Moon (Moon code, Moon script, Moon type)');
insert into vocabulary (type, value, description) values ('script_code', 'Mroo', 'Mro, Mru');
insert into vocabulary (type, value, description) values ('script_code', 'Mtei', 'Meitei Mayek (Meithei, Meetei)');
insert into vocabulary (type, value, description) values ('script_code', 'Mult', 'Multani');
insert into vocabulary (type, value, description) values ('script_code', 'Mymr', 'Myanmar (Burmese)');
insert into vocabulary (type, value, description) values ('script_code', 'Narb', 'Old North Arabian (Ancient North Arabian)');
insert into vocabulary (type, value, description) values ('script_code', 'Nbat', 'Nabataean');
insert into vocabulary (type, value, description) values ('script_code', 'Newa', 'Newa, Newar, Newari, Nepāla lipi');
insert into vocabulary (type, value, description) values ('script_code', 'Nkgb', 'Nakhi Geba ('Na-'Khi ²Ggŏ-¹baw, Naxi Geba)');
insert into vocabulary (type, value, description) values ('script_code', 'Nkoo', 'N’Ko');
insert into vocabulary (type, value, description) values ('script_code', 'Nshu', 'Nüshu');
insert into vocabulary (type, value, description) values ('script_code', 'Ogam', 'Ogham');
insert into vocabulary (type, value, description) values ('script_code', 'Olck', 'Ol Chiki (Ol Cemet’, Ol, Santali)');
insert into vocabulary (type, value, description) values ('script_code', 'Orkh', 'Old Turkic, Orkhon Runic');
insert into vocabulary (type, value, description) values ('script_code', 'Orya', 'Oriya');
insert into vocabulary (type, value, description) values ('script_code', 'Osge', 'Osage');
insert into vocabulary (type, value, description) values ('script_code', 'Osma', 'Osmanya');
insert into vocabulary (type, value, description) values ('script_code', 'Palm', 'Palmyrene');
insert into vocabulary (type, value, description) values ('script_code', 'Pauc', 'Pau Cin Hau');
insert into vocabulary (type, value, description) values ('script_code', 'Perm', 'Old Permic');
insert into vocabulary (type, value, description) values ('script_code', 'Phag', 'Phags-pa');
insert into vocabulary (type, value, description) values ('script_code', 'Phli', 'Inscriptional Pahlavi');
insert into vocabulary (type, value, description) values ('script_code', 'Phlp', 'Psalter Pahlavi');
insert into vocabulary (type, value, description) values ('script_code', 'Phlv', 'Book Pahlavi');
insert into vocabulary (type, value, description) values ('script_code', 'Phnx', 'Phoenician');
insert into vocabulary (type, value, description) values ('script_code', 'Plrd', 'Miao (Pollard)');
insert into vocabulary (type, value, description) values ('script_code', 'Piqd', 'Klingon (KLI pIqaD)');
insert into vocabulary (type, value, description) values ('script_code', 'Prti', 'Inscriptional Parthian');
insert into vocabulary (type, value, description) values ('script_code', 'Qaaa', 'Reserved for private use (start)');
insert into vocabulary (type, value, description) values ('script_code', 'Qabx', 'Reserved for private use (end)');
insert into vocabulary (type, value, description) values ('script_code', 'Rjng', 'Rejang (Redjang, Kaganga)');
insert into vocabulary (type, value, description) values ('script_code', 'Roro', 'Rongorongo');
insert into vocabulary (type, value, description) values ('script_code', 'Runr', 'Runic');
insert into vocabulary (type, value, description) values ('script_code', 'Samr', 'Samaritan');
insert into vocabulary (type, value, description) values ('script_code', 'Sara', 'Sarati');
insert into vocabulary (type, value, description) values ('script_code', 'Sarb', 'Old South Arabian');
insert into vocabulary (type, value, description) values ('script_code', 'Saur', 'Saurashtra');
insert into vocabulary (type, value, description) values ('script_code', 'Sgnw', 'SignWriting');
insert into vocabulary (type, value, description) values ('script_code', 'Shaw', 'Shavian (Shaw)');
insert into vocabulary (type, value, description) values ('script_code', 'Shrd', 'Sharada, Śāradā');
insert into vocabulary (type, value, description) values ('script_code', 'Sidd', 'Siddham, Siddhaṃ, Siddhamātṛkā');
insert into vocabulary (type, value, description) values ('script_code', 'Sind', 'Khudawadi, Sindhi');
insert into vocabulary (type, value, description) values ('script_code', 'Sinh', 'Sinhala');
insert into vocabulary (type, value, description) values ('script_code', 'Sora', 'Sora Sompeng');
insert into vocabulary (type, value, description) values ('script_code', 'Sund', 'Sundanese');
insert into vocabulary (type, value, description) values ('script_code', 'Sylo', 'Syloti Nagri');
insert into vocabulary (type, value, description) values ('script_code', 'Syrc', 'Syriac');
insert into vocabulary (type, value, description) values ('script_code', 'Syre', 'Syriac (Estrangelo variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Syrj', 'Syriac (Western variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Syrn', 'Syriac (Eastern variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Tagb', 'Tagbanwa');
insert into vocabulary (type, value, description) values ('script_code', 'Takr', 'Takri, Ṭākrī, Ṭāṅkrī');
insert into vocabulary (type, value, description) values ('script_code', 'Tale', 'Tai Le');
insert into vocabulary (type, value, description) values ('script_code', 'Talu', 'New Tai Lue');
insert into vocabulary (type, value, description) values ('script_code', 'Taml', 'Tamil');
insert into vocabulary (type, value, description) values ('script_code', 'Tang', 'Tangut');
insert into vocabulary (type, value, description) values ('script_code', 'Tavt', 'Tai Viet');
insert into vocabulary (type, value, description) values ('script_code', 'Telu', 'Telugu');
insert into vocabulary (type, value, description) values ('script_code', 'Teng', 'Tengwar');
insert into vocabulary (type, value, description) values ('script_code', 'Tfng', 'Tifinagh (Berber)');
insert into vocabulary (type, value, description) values ('script_code', 'Tglg', 'Tagalog (Baybayin, Alibata)');
insert into vocabulary (type, value, description) values ('script_code', 'Thaa', 'Thaana');
insert into vocabulary (type, value, description) values ('script_code', 'Thai', 'Thai');
insert into vocabulary (type, value, description) values ('script_code', 'Tibt', 'Tibetan');
insert into vocabulary (type, value, description) values ('script_code', 'Tirh', 'Tirhuta');
insert into vocabulary (type, value, description) values ('script_code', 'Ugar', 'Ugaritic');
insert into vocabulary (type, value, description) values ('script_code', 'Vaii', 'Vai');
insert into vocabulary (type, value, description) values ('script_code', 'Visp', 'Visible Speech');
insert into vocabulary (type, value, description) values ('script_code', 'Wara', 'Warang Citi (Varang Kshiti)');
insert into vocabulary (type, value, description) values ('script_code', 'Wole', 'Woleai');
insert into vocabulary (type, value, description) values ('script_code', 'Xpeo', 'Old Persian');
insert into vocabulary (type, value, description) values ('script_code', 'Xsux', 'Cuneiform, Sumero-Akkadian');
insert into vocabulary (type, value, description) values ('script_code', 'Yiii', 'Yi');
insert into vocabulary (type, value, description) values ('script_code', 'Zinh', 'Code for inherited script');
insert into vocabulary (type, value, description) values ('script_code', 'Zmth', 'Mathematical notation');
insert into vocabulary (type, value, description) values ('script_code', 'Zsye', 'Symbols (Emoji variant)');
insert into vocabulary (type, value, description) values ('script_code', 'Zsym', 'Symbols');
insert into vocabulary (type, value, description) values ('script_code', 'Zxxx', 'Code for unwritten documents');
insert into vocabulary (type, value, description) values ('script_code', 'Zyyy', 'Code for undetermined script');
insert into vocabulary (type, value, description) values ('script_code', 'Zzzz', 'Code for uncoded script');
