#!/usr/bin/env php
<?php
/**
 * Tear down and rebuild Concept Vocabulary tables
 *
 *
 * @author Joseph Glass
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2018 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../vendor/autoload.php";

use \snac\Config as Config;
use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Handler
// $cStore = new \snac\server\database\DBUtil();
// $uStore = new \snac\server\database\DBUser();
// $db = new \snac\server\database\DatabaseConnector();

$host = Config::$DATABASE["host"];
$port = Config::$DATABASE["port"];
$database = Config::$DATABASE["database"];
$password = Config::$DATABASE["password"];
$user = Config::$DATABASE["user"];

$dbHandle = pg_connect("host=$host port=$port dbname=$database user=$user password=$password");

$result = pg_query($dbHandle, file_get_contents("../install/sql_files/concept_vocabulary.sql"));


if (!$result) {
    $error = pg_last_error($dbHandle);
    echo "Error: Concept Vocab tables not correctly built \n";
    echo $error."\n";
}
