#!/usr/bin/env php
<?php
/**
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// Did we parse a file?
$parsedFile = false;

// SNAC Postgres DB Handler
$dbu = new snac\server\database\DBUtil();

// SNAC Postgres User Handler
$dbuser = new \snac\server\database\DBUser();
$tempUser = new \snac\data\User();
$tempUser->setUserName("system@localhost");
$user = $dbuser->readUser($tempUser);
$user->generateTemporarySession();

// ElasticSearch Handler
$eSearch = null;
if (\snac\Config::$USE_ELASTIC_SEARCH) {
    $eSearch = Elasticsearch\ClientBuilder::create()
        ->setHosts([\snac\Config::$ELASTIC_SEARCH_URI])
        ->setRetries(0)
        ->build();
}

$line = file($argv[1], FILE_IGNORE_NEW_LINES);


foreach ($line as $data) {
    list ($ark, $junk) = explode(",",$data);

    list($junk, $parts) = explode("ark:/", $ark);
    $arkid = "http://n2t.net/ark:/" . $parts;

    $parsedFile = true;

    $check = $dbu->readPublishedConstellationByARK($arkid, true);

    if ($check === false)
        die ("Error finding institution " . $arkid);
    /*
     * Add to the snac_institution table. An institution is a constellation, usually in summary form. The
     * institution code only cares about the constellation ID aka ic_id, from getID().
     */
    $dbuser->writeInstitution($check);
    printf("Added to table snac_institutions: %s (ARK: %s)\n", $check->getID(), $check->getArk());

}


// If no file was parsed, then print the output that something went wrong
if ($parsedFile == false) {
    echo "No arks given\n\n"
        . "Sample usage: ./ingest_institutions.php list.txt\n\n";
}
