#!/usr/bin/env php
<?php
/**
 * Parse an EAC-CPF record and return a JSON object 
 * 
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */

// Include the global autoloader generated by composer
include "vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// If no file was parsed, then print the output that something went wrong
if ($argc < 2) {
    echo "No files given\n\n"
        . "Sample usage: ./parse_eac_to_json filename.json\n\n";

} else {

    $const = new \snac\data\Constellation(json_decode(file_get_contents($argv[1]), true));

    $eSerializer = new \snac\util\EACCPFSerializer();

    $cpfXML = $eSerializer->serialize($const);

    echo $cpfXML;
}
