#!/usr/bin/env php
<?php
/**
 * Fix the vocabulary 
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler("sql_queries.log", Logger::DEBUG);

// SNAC Database Connectior
$db = new snac\server\database\DatabaseConnector();

$query = "";
switch ($argv[1]) {
    case "placelink":
        $query = "update place_link set confirmed = true where (id, version) in (select pl.id, pl.version from place_link pl, geo_place g where pl.geo_place_id = g.id and not pl.confirmed and g.uri is null) returning *;";
        break;
    case "nullrelations":
        $query = "delete from related_identity where related_id is null and (related_ark is null or related_ark = '') returning *;";
        break;
    case "removeresourcenote":
        $query = "update related_resource set descriptive_note = null where descriptive_note like '%socialarchive.iath.virginia.edu/control/term%' returning *";
        break;
}

if ($query == "")
    die ("could not perform action");

$result = $db->query($query, array());

while ($res = $db->fetchRow($result)) {
    echo json_encode($res, JSON_PRETTY_PRINT);
}

