#!/usr/bin/env php
<?php
/**
 * Bulk update of resource hrefs from a csv file
 *
 *
 * @author Joseph Glass
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2018 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Handler
// $cStore = new \snac\server\database\DBUtil();
// $uStore = new \snac\server\database\DBUser();

$db = new \snac\server\database\DatabaseConnector();

$handle = fopen("new_harvard_links.csv", "r");

echo 'parsing harvard href csv';

if(($handle !== false)) {

    $db->prepare("href_update", "UPDATE resource_cache SET href = $1 WHERE id = $2");
    while (($data = fgetcsv($handle, 1000, ',')) !== false) {
        $id = $data[0];
        $newHref = $data[2];
        $db->execute("href_update", array($newHref, $id));
    }
}
