#!/usr/bin/env php
<?php
/**
 * Bulk update of resource hrefs from a csv file
 *
 *
 * @author Joseph Glass
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2018 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

if (\snac\Config::$USE_ELASTIC_SEARCH) {
    $eSearch = Elasticsearch\ClientBuilder::create()
    ->setHosts([\snac\Config::$ELASTIC_SEARCH_URI])
    ->setRetries(0)
    ->build();
}


$elasticSearch = new \snac\server\elastic\ElasticSearchUtil();

// $elasticSearch->updateResourceField(11614417, 'url', 'ESupdate.com');

// SNAC Postgres DB Handler
// $cStore = new \snac\server\database\DBUtil();
// $uStore = new \snac\server\database\DBUser();

// $db = new \snac\server\database\DatabaseConnector();

$handle = fopen("new_harvard_links.csv", "r");

echo 'updating ES hrefs';
//
if(($handle !== false)) {
//
    while (($data = fgetcsv($handle, 1000, ',')) !== false) {
        $id = $data[0];
        $newHref = $data[2];
        $elasticSearch->updateResourceField($id, 'url', $newHref);
    }
}


echo "\ndone!\n";


// updateElasticsearchResource($id, $field, $value)
