#!/usr/bin/env php
<?php
/**
 * Bulk update of resource hrefs from a csv file
 *
 *
 * @author Joseph Glass
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2018 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../vendor/autoload.php";

// use \Monolog\Logger;
// use \Monolog\Handler\StreamHandler;

// Set up the global log stream
// $log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

$db = new \snac\server\database\DatabaseConnector();

$fh = fopen("si_new_urls.csv", "r");

if(($fh !== false)) {
    $is_header = true;
    $db->prepare("href_update", "UPDATE resource_cache SET href = $1 WHERE id = $2");
    while (($data = fgetcsv($fh, 1000, ',')) !== false) {
        if ($is_header) { $is_header = false; continue; }

        $id = $data[0];
        $new_href = $data[4];
        echo "updating $id to $new_href \n";
        $db->execute("href_update", array($new_href, $id));
    }
}
