#!/usr/bin/env php
<?php
/**
 * Create up to date versions of two files critical to testing. You must manually overwrite the old file with
 * the new after running this script.
 *
 * @author Robbie Hott 
 * @author Tom Laudeman
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */

// Include the global autoloader generated by composer
include "vendor/autoload.php";

// We cannot build the new from the old if the data structures change!
//$jsonIn = file_get_contents("test/snac/data/json/constellation_test.json");
//$identity->fromJSON($jsonIn);
$e = new \snac\util\EACCPFParser();
// Parse the FRAN data from the test suite 
$identity = $e->parseFile("test/snac/util/eac-cpf/FRAN_NP_050744.xml");
file_put_contents("test/snac/data/json/constellation_test_v2.json", $identity->toJSON(false));
printf("Wrote: test/snac/data/json/constellation_test_v2.json\n");

$e = new \snac\util\EACCPFParser();
// Parse Thomas Jefferson's EAC-CPF from the internet
$identity = $e->parseFile("http://socialarchive.iath.virginia.edu/snac/data/99166-w6w9576g.xml");
file_put_contents("test/snac/data/json/constellation_test2_v2.json", $identity->toJSON(false));
printf("Wrote: test/snac/data/json/constellation_test2_v2.json\n");

printf("WARNING: test/snac/data/json/constellation_simple.json cannot be automatically updated.\n");
