#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
/**
 * Refresh the Elatic Search Indices
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

$batchSize = 100000;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();


echo "Querying the names from the database.\n";
pg_query($db->getHandle(),"DROP TABLE IF EXISTS _elastic_names;");
pg_query($db->getHandle(),"CREATE TABLE _elastic_names (
    ic_id integer not null primary key
    , name_entry text 
    , names_variant text[]
    , entity_type text
    , ark_id text
    , degree integer
    , resources integer
    , subject text[]
    , occupation text[]
    , activity text[]
    , biog_hist text[]
        );");
pg_query($db->getHandle(),"DROP TABLE IF EXISTS _elastic_names_secondary;");
pg_query($db->getHandle(),"CREATE TABLE _elastic_names_secondary(
    name_id integer not null
    , name_entry text 
    , entity_type text 
    , ark_id text
    , ic_id integer not null
    , preference_score double precision
    , degree integer
    , resources integer
        );");

pg_query($db->getHandle(),"BEGIN");
pg_query($db->getHandle(),"INSERT INTO _elastic_names_secondary (ic_id,ark_id,name_id,name_entry,preference_score,entity_type)
  (select one.ic_id, one.ark_id, two.id as name_id, two.original, two.preference_score, one.entity_type from
    (select
        aa.is_deleted,aa.id,aa.version, aa.ic_id, aa.original, aa.preference_score
    from
        name as aa,
        (select name.id,max(name.version) as version from name
            left join (select v.id as ic_id, v.version, nrd.ark_id
                    from version_history v
                    left join (select bb.id, max(bb.version) as version from
                    (select id, version from version_history where status in ('published', 'deleted', 'tombstone')) bb
                    group by id order by id asc) mv
                    on v.id = mv.id and v.version = mv.version
                    left join nrd on v.id = nrd.ic_id
                    where
                    v.status = 'published'
                    order by v.id asc, v.version desc) vh
                on name.version<=vh.version and
                name.ic_id=vh.ic_id
            group by name.id) as bb
    where
        aa.id = bb.id and
        not aa.is_deleted and
        aa.version = bb.version
    order by ic_id asc, preference_score desc, id asc) two,
    (select v.id as ic_id, v.version, n.ark_id, etv.value as entity_type
    from
        version_history v,
        (select bb.id, max(bb.version) as version from
            (select id, version from version_history where status in ('published', 'deleted', 'tombstone')) bb
            group by id order by id asc) mv,
        vocabulary etv,
        nrd n
    where
        v.id = mv.id and
        v.version = mv.version and
        v.status = 'published' and
        v.id = n.ic_id and
        n.ark_id is not null and
        n.entity_type = etv.id) one
where
    two.ic_id = one.ic_id
order by
    one.ic_id asc, two.preference_score desc, two.id asc);");
pg_query($db->getHandle(),"CREATE INDEX _elastic_names_secondary_ndx_1 on _elastic_names_secondary (ic_id);");
pg_query($db->getHandle(),"COMMIT");

echo "Updating names.\n";
$previousICID = -1;
$db->cursorQuery("allNames","select ic_id, ark_id, name_id, name_entry, preference_score, entity_type
        from _elastic_names_secondary
        order by ic_id asc, preference_score desc, name_id asc");
$db->prepare("updateMain","insert into _elastic_names (ic_id, name_entry, entity_type, ark_id) values (\$1,\$2,\$3,\$4)");
$count = 0;
while ($resource = $db->cursorFetch("allNames",$batchSize)) {
    if (pg_num_rows($resource) == 0) { break; }

        while($name = $db->fetchrow($resource)) {
            $count++;
            if ($previousICID != $name["ic_id"]) {
                $updateResult = $db->execute("updateMain",array($name["ic_id"],$name["name_entry"],$name["entity_type"],$name["ark_id"]));
            }
            $previousICID = $name["ic_id"];
    }
    pg_free_result($resource);
    if ($count % 100000 == 0) { echo "$count...\n"; }
}
$db->cursorClose("allNames");

echo "Adding variant names.\n";
pg_query($db->getHandle(),"UPDATE _elastic_names n SET names_variant=s.names FROM
    (select ic_id, array_agg(name_entry) as names from _elastic_names_secondary group by ic_id) s
    WHERE n.ic_id = s.ic_id");

echo "Done\n";
