#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
/**
 * Refresh the Elatic Search Indices
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

$batchSize = 100000;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();


$countQry = pg_query($db->getHandle(),"DROP TABLE IF EXISTS _elastic_relational;");
$countQry = pg_query($db->getHandle(),"CREATE TABLE _elastic_relational (
    ic_id integer not null primary key
    , degree integer DEFAULT 0
    , resources integer DEFAULT 0
    , subject text[]
    , occupation text[]
    , activity text[]
    , biog_hist text[]
        );");

echo "Inserting stub records.\n";
$db->query("INSERT INTO _elastic_relational (ic_id) SELECT ic_id from _elastic_names", array());

echo "Querying the relation degrees from the database.\n";

$db->query("UPDATE _elastic_relational r
        SET degree = q.degree
        FROM (SELECT a.ic_id, count(*) as degree from
            (select r.id, r.ic_id from
                related_identity r,
                (select distinct id, max(version) as version from related_identity group by id) a
                where a.id = r.id and a.version = r.version and not r.is_deleted) a
                group by ic_id) q
        WHERE r.ic_id = q.ic_id", array());

echo "Querying the resource relation degrees from the database.\n";

$db->query("UPDATE _elastic_relational r
        SET resources = q.resources
        FROM (select a.ic_id, count(*) as resources from
            (select r.id, r.ic_id from
                related_resource r,
                (select distinct id, max(version) as version from related_resource group by id) a
                where a.id = r.id and a.version = r.version and not r.is_deleted) a
                group by ic_id) q
        WHERE r.ic_id = q.ic_id", array());

echo "Querying the controlled vocabulary terms (subject) from the database:\n";
$vocabQuery = $db->query("select distinct aa.ic_id, aa.concept_id as term_id, v.text as term_value
            from identity_concepts aa
            left outer join terms v on aa.concept_id = v.concept_id
	    inner join (select id, max(version) as version from identity_concepts where type='subject' group by id) as bb
	    on aa.id=bb.id and aa.version=bb.version where v.preferred and not aa.is_deleted
            and aa.type='subject' order by aa.ic_id,v.text;", array());
pg_query($db->getHandle(),"BEGIN");
$updateCount = $db->prepare("subject_terms","update _elastic_relational set subject=array_append(COALESCE(subject, '{}'),\$2) where ic_id=\$1");
$n = 0;
while($v = $db->fetchrow($vocabQuery))
{
    $result = $db->execute("subject_terms",array($v["ic_id"],$v["term_value"]));
    $n++; if ($n % 100000 == 0) { echo "$n...\n"; }
}
pg_query($db->getHandle(),"COMMIT");


echo "Querying the controlled vocabulary terms (occupation) from the database:\n";
pg_query($db->getHandle(),"BEGIN");
$vocabQuery = $db->query("select distinct aa.ic_id, aa.concept_id as term_id, v.text as term_value
            from identity_concepts aa
            left outer join terms v on aa.concept_id = v.concept_id
	    inner join (select id, max(version) as version from identity_concepts where type='occupation' group by id) as bb
	    on aa.id=bb.id and aa.version=bb.version where v.preferred and not aa.is_deleted
            and aa.type='occupation' order by aa.ic_id,v.text;", array());
$countSQL = pg_query($db->getHandle(),"BEGIN");
$updateCount = $db->prepare("occupation_terms","update _elastic_relational set occupation=array_append(COALESCE(occupation, '{}'),\$2) where ic_id=\$1");
$n = 0;
while($v = $db->fetchrow($vocabQuery))
{
    $result = $db->execute("occupation_terms",array($v["ic_id"],$v["term_value"]));
    $n++; if ($n % 100000 == 0) { echo "$n...\n"; }
}
pg_query($db->getHandle(),"COMMIT");


echo "Querying the controlled vocabulary terms (activity) from the database:\n";
pg_query($db->getHandle(),"BEGIN");
$vocabQuery = $db->query("select distinct aa.ic_id, aa.concept_id as term_id, v.text as term_value
            from identity_concepts aa
            left outer join terms v on aa.concept_id = v.concept_id
	    inner join (select id, max(version) as version from identity_concepts where type='activity' group by id) as bb
	    on aa.id=bb.id and aa.version=bb.version where v.preferred and not aa.is_deleted
            and aa.type='activity' order by aa.ic_id,v.text;", array());
$countSQL = pg_query($db->getHandle(),"BEGIN");
$updateCount = $db->prepare("activity_terms","update _elastic_relational set activity=array_append(COALESCE(activity, '{}'),\$2) where ic_id=\$1");
$n = 0;
while($v = $db->fetchrow($vocabQuery))
{
    $result = $db->execute("activity_terms",array($v["ic_id"],$v["term_value"]));
    $n++; if ($n % 100000 == 0) { echo "$n...\n"; }
}
pg_query($db->getHandle(),"COMMIT");
$vocab = array();


echo "Querying the BiogHists\n";
pg_query($db->getHandle(),"BEGIN");
$biogHistQuery = pg_query($db->getHandle(),"UPDATE _elastic_relational c SET biog_hist=b.text FROM
            (select v.ic_id, array_agg(v.text) as text from
                biog_hist v,
                (select distinct id, max(version) as version from biog_hist group by id) a
                where a.id = v.id and a.version = v.version and not v.is_deleted group by v.ic_id) b
            WHERE c.ic_id = b.ic_id;");
pg_query($db->getHandle(),"COMMIT");

echo "Done\n";
