#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
/**
 * Refresh the Elatic Search Indices
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();


pg_query($db->getHandle(),"CREATE TABLE IF NOT EXISTS _elastic_images (
    ic_id integer not null primary key
    , ark_id text
    , image_url text
    , image_metadata text
    , is_featured_image boolean DEFAULT false
);");
pg_query($db->getHandle(),"CREATE INDEX _elastic_images_ndx_1 ON _elastic_images (ark_id)");

echo "Done\n";
