#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
/**
 * Refresh the Elatic Search Indices
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

$batchSize = 100000;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();


// ElasticSearch Handler
$eSearch = null;

$primaryCount = 0;
$secondaryCount = 0;
$primaryStart = false;
$secondaryStart = false;
$primaryBody = array();
$secondaryBody = array();

if (!(\snac\Config::$USE_ELASTIC_SEARCH)) {
    die("This version of SNAC does not currently use Elastic Search.  Please check your configuration file.\n");
}

$eSearch = Elasticsearch\ClientBuilder::create()
    ->setHosts([\snac\Config::$ELASTIC_SEARCH_URI])
    ->setRetries(0)
    ->build();

echo "Trying to delete the Elastic Search Index: " . \snac\Config::$ELASTIC_SEARCH_BASE_INDEX . "\n";
try {
    $params = array("index" => \snac\Config::$ELASTIC_SEARCH_BASE_INDEX);
    $response = $eSearch->indices()->delete($params);
    echo "   - deleted search index\n";
} catch (\Exception $e) {
    echo "   - could not delete search index. It did not exist.\n";
}
/*
try {
    $params = array("index" => \snac\Config::$ELASTIC_SEARCH_ALL_INDEX);
    $response = $eSearch->indices()->delete($params);
    echo "   - deleted secondary search index\n";
} catch (\Exception $e) {
    echo "   - could not delete secondary search index. It did not exist.\n";
}
*/

echo "Trying to create the Elastic Search Index: " . \snac\Config::$ELASTIC_SEARCH_BASE_INDEX . "\n";
try {
    $params = [
        "index" => \snac\Config::$ELASTIC_SEARCH_BASE_INDEX,
        "body" => [
            "settings" => [
                "analysis" => [
                    "analyzer" => [
                        "standard_asciifolding" => [
                            "tokenizer" => "standard",
                            "preserve_original" => "true",
                            "filter" => ["lowercase", "asciifolding"]
                        ]
                    ]
                ]
            ],
            "mappings" => [
                "properties"=> [
                    "arkID"=> [
                        "type"=> "keyword"
                    ],
                    "biogHist"=> [
                        "type"=> "text"
                    ],
                    "degree"=> [
                        "type"=> "long"
                    ],
                    "entityType"=> [
                        "type"=> "keyword",
                    ],
                    "activity"=> [
                        "type"=> "keyword",
                    ],
                    "hasImage"=> [
                        "type"=> "boolean"
                    ],
                    "hasFeaturedImage"=> [
                        "type"=> "boolean"
                    ],
                    "id"=> [
                        "type"=> "long"
                    ],
                    "imageMeta"=> [
                        "properties"=> [
                            "author"=> [
                                "properties"=> [
                                    "name"=> [
                                        "type"=> "keyword"
                                    ],
                                    "url"=> [
                                        "type"=> "keyword"
                                    ]
                                ]
                            ],
                            "info"=> [
                                "type"=> "keyword"
                            ],
                            "infoURL"=> [
                                "type"=> "keyword"
                            ],
                            "license"=> [
                                "properties"=> [
                                    "name"=> [
                                        "type"=> "keyword"
                                    ],
                                    "url"=> [
                                        "type"=> "keyword"
                                    ]
                                ]
                            ]
                        ]
                    ],
                    "imageURL"=> [
                        "type"=> "keyword"
                    ],
                    "nameEntry"=> [
                        "type"=> "text",
                        "analyzer" => "standard_asciifolding",
                    ],
                    "nameVariants"=> [
                        "type"=> "text",
                        "analyzer" => "standard_asciifolding",
                    ],
                    "occupation"=> [
                        "type"=> "keyword",
                    ],
                    "resources"=> [
                        "type"=> "long"
                    ],
                    "subject"=> [
                        "type"=> "keyword",
                    ],
                    "timestamp"=> [
                        "format"=> "strict_date_optional_time||epoch_millis",
                        "type"=> "date"
                    ]
                ]
            ]
        ]
    ];
    $response = $eSearch->indices()->create($params);
    echo "   - created search index\n";
    sleep(10);
} catch (\Exception $e) {
    // echo "   - could not create search index\n";
    var_dump($e);
    die("   - could not create search index");
}



$count = 0;
echo "Updating the Elastic Search indices. This may take a while...\n";
$db->cursorQuery("indexMain","select n.ic_id, n.name_entry, n.names_variant, 
        n.entity_type, n.ark_id, r.degree, r.resources,
        array_to_json(r.subject) as subject, array_to_json(r.occupation) as occupation,
        array_to_json(r.activity) as activity, r.biog_hist,
        i.image_url, i.image_metadata, i.is_featured_image::int
           from _elastic_names n
            left join _elastic_relational r on n.ic_id = r.ic_id
            left join _elastic_images i on n.ic_id = i.ic_id");
while ($resource = $db->cursorFetch("indexMain",$batchSize)) {
    if (pg_num_rows($resource) == 0) { break; }
    while($name = $db->fetchrow($resource)) {
            $subject = json_decode($name["subject"]);
            $occupation = json_decode($name["occupation"]);
            $activity = json_decode($name["activity"]);
            $metadata = json_decode($name["image_metadata"]);

            indexMain($name["name_entry"], $name["names_variant"], $name["ark_id"], (int) $name["ic_id"], $name["entity_type"], $name["degree"], $name["resources"], $subject, $occupation, $activity, $name["biog_hist"],$name["image_url"],$metadata,$name["is_featured_image"]);
            $count++;
    }
    pg_free_result($resource);
    echo substr("$count    ",0,8);
}
$db->cursorClose("indexMain");

echo "Cleaning up last bulk updates\n";
bulkUpdate($primaryBody, $primaryCount);

/*
$count = 0;
$db->cursorQuery("indexSecondary","select n.ic_id,n.name_id,n.name_entry,n.entity_type,n.ark_id,r.degree,r.resources
           from _elastic_names_secondary n
            left join _elastic_relational r on n.ic_id = r.ic_id");
while ($resource = $db->cursorFetch("indexSecondary",$batchSize)) {
    if (pg_num_rows($resource) == 0) { break; }
    while($name = $db->fetchrow($resource)) {
        $count++;
        indexSecondary($name["name_entry"], $name["ark_id"], (int) $name["ic_id"], (int) $name["name_id"], $name["entity_type"], $name["degree"], $name["resources"]);
    }
    pg_free_result($resource);
    echo substr("$count    ",0,8);
}
echo "Cleaning up last bulk updates\n";
bulkUpdate($secondaryBody, $secondaryCount);
 */


function indexMain($nameText, $nameVariants, $ark, $icid, $entityType, $degree, $resources, $subject, $occupation, $activity, $biogHist, $imgURL, $imgMeta, $imgFeatured) {
    global $eSearch, $primaryBody, $primaryStart, $primaryCount, $batchSize;
    
    $degree ??= 0;
    $resources ??= 0;
    $subject ??= array();
    $occupation ??= array();
    $activity ??= array();
    $biogHist ??= array();
    $nameVariants ??= array();

    $hasImage = false;
    $hasFeaturedImage = false;
    if ($imgURL) { $hasImage = true; }
    if ($hasImage && $imgFeatured) { $hasFeaturedImage = true; }


    if ($eSearch != null) {
        // do one first to get the index going
        if (!$primaryStart) {
            $params = [
                    'index' => \snac\Config::$ELASTIC_SEARCH_BASE_INDEX,
                    'id' => $icid,
                    'body' => [
                            'nameEntry' => $nameText,
                            'nameVariants' => $nameVariants,
                            'entityType' => $entityType,
                            'arkID' => $ark,
                            'id' => $icid,
                            'degree' => $degree,
                            'resources' => $resources,
                            'subject' => $subject,
                            'occupation' => $occupation,
                            'activity' => $activity,
                            'biogHist' => $biogHist,
                            'hasImage' => $hasImage,
                            'hasFeaturedImage' => $hasFeaturedImage,
                            'imageURL' => $imgURL,
                            'imageMeta' => $imgMeta,
                            'timestamp' => date("c")
                    ]
            ];

            $eSearch->index($params);
            $primaryStart = true;
        } else {
            if ($primaryCount >= $batchSize) {
                echo "  Running Primary bulk update\n";
                bulkUpdate($primaryBody, $primaryCount);
            }
            $primaryBody['body'][] = [
                'index' => [
                    '_index' => \snac\Config::$ELASTIC_SEARCH_BASE_INDEX,
                    '_id' => $icid
                ]
            ];
            $primaryBody['body'][] = [
                'nameEntry' => $nameText,
                'nameVariants' => $nameVariants,
                'entityType' => $entityType,
                'arkID' => $ark,
                'id' => $icid,
                'degree' => $degree,
                'resources' => $resources,
                'subject' => $subject,
                'occupation' => $occupation,
                'activity' => $activity,
                'biogHist' => $biogHist,
                'hasImage' => $hasImage,
                'hasFeaturedImage' => $hasFeaturedImage,
                'imageURL' => $imgURL,
                'imageMeta' => $imgMeta,
                'timestamp' => date("c")
            ];
            $primaryCount++;
        }
    }
}


function indexSecondary($nameText, $ark, $icid, $nameid, $entityType, $degree, $resources) {
    global $eSearch, $secondaryBody, $secondaryStart, $secondaryCount, $batchSize;
    $degree ??= 0;
    $resources ??= 0;

    if ($eSearch != null) {
        // do one first to get the index going
        if (!$secondaryStart) {
            $params = [
                    // 'index' => \snac\Config::$ELASTIC_SEARCH_BASE_INDEX,
                    'index' => \snac\Config::$ELASTIC_SEARCH_ALL_INDEX,
                    'id' => $nameid,
                    'body' => [
                            'nameEntry' => $nameText,
                            'entityType' => $entityType,
                            'arkID' => $ark,
                            'id' => $icid,
                            'name_id' => $nameid,
                            'degree' => $degree,
                            'resources' => $resources,
                            'timestamp' => date("c")
                    ]
            ];

            $eSearch->index($params);
            $secondaryStart = true;
        } else {
            if ($secondaryCount >= $batchSize) {
                echo "  Running Secondary bulk update\n";
                bulkUpdate($secondaryBody, $secondaryCount);
            }
            // elasticsearch api = array with "index" => array(information), followed by array of data, then repeated
            $secondaryBody['body'][] = [
                'index' => [
                    // '_index' => \snac\Config::$ELASTIC_SEARCH_BASE_INDEX,
                    '_index' => \snac\Config::$ELASTIC_SEARCH_ALL_INDEX,
                    '_id' => $nameid
                ]
            ];
            $secondaryBody['body'][] = [
                'nameEntry' => $nameText,
                'entityType' => $entityType,
                'arkID' => $ark,
                'id' => $icid,
                'name_id' => $nameid,
                'degree' => $degree,
                'resources' => $resources,
                'timestamp' => date("c")
            ];
            $secondaryCount++;
        }
    }
}

function bulkUpdate(&$body, &$count) {
    global $eSearch;
    if ($eSearch != null) {
        $count = 0;

        $responses = $eSearch->bulk($body);

        if ($responses['errors'] === true) {
            foreach ($responses['items'] as $item) {
                if (isset($item['index']['error'])) {
                    print_r($item['index']['error'])."\n";
                }
            }
        }

        // erase the old bulk request
        $body = array();

        // unset the bulk response when you are done to save memory
        unset($responses);
    }
}

echo "Done.\n";

