#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
/**
 * Refresh the Elatic Search Indices
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

$batchSize = 100000;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();

$ids = array();
$ids[] = 87657525;
$ids[] = 87659434;
$ids[] = 87659525;
$ids[] = 25965491;
$ids[] = 47625542;
$ids[] = 86615831;
$ids[] = 48395160;
$ids[] = 67192212;
$ids[] = 83393344;
$ids[] = 83843060;
$ids[] = 83847206;
$ids[] = 87782405;
$ids[] = 87782253;
$ids[] = 69848709;
$ids[] = 87783199;
$ids[] = 87783305;
$ids[] = 7870084;
$ids[] = 68857378;
$ids[] = 87783766;
$ids[] = 87788636;
$ids[] = 27387084;
$ids[] = 85415038;
$ids[] = 21930565;
$ids[] = 44914451;
$ids[] = 87801718;
$ids[] = 87801861;
$ids[] = 87809591;
$ids[] = 87809715;
$ids[] = 83877134;
$ids[] = 52950819;
$ids[] = 87809809;
$ids[] = 85832412;
$ids[] = 67338998;
$ids[] = 87809923;
$ids[] = 87810077;
$ids[] = 52844840;
$ids[] = 86724130;
$ids[] = 84912582;
$ids[] = 83430505;
$ids[] = 86807122;
$ids[] = 84546768;
$ids[] = 63662586;
$ids[] = 11191855;
$ids[] = 87811473;
$ids[] = 84217756;
$ids[] = 87811516;
$ids[] = 87811558;
$ids[] = 87812276;
$ids[] = 63116286;
$ids[] = 35564552;
$ids[] = 87812428;
$ids[] = 87813239;
$ids[] = 83285690;
$ids[] = 87813637;
$ids[] = 2698518;
$ids[] = 47018863;
$ids[] = 87813686;
$ids[] = 87815980;
$ids[] = 31185957;
$ids[] = 87817610;
$ids[] = 87817698;
$ids[] = 9865771;
$ids[] = 87818037;
$ids[] = 87536789;
$ids[] = 37900769;
$ids[] = 87824746;
$ids[] = 39715598;
$ids[] = 87824899;
$ids[] = 24469433;
$ids[] = 87899587;
$ids[] = 39575056;
$ids[] = 32337738;
$ids[] = 61876892;
$ids[] = 19866811;
$ids[] = 76521631;
$ids[] = 73693874;
$ids[] = 69874026;
$ids[] = 12898076;
#Cochran, Jacqueline, 1906?-1980: http://n2t.net/ark:/99166/w6010rmb
#Australian Women's Land Army: http://n2t.net/ark:/99166/w64853tq

$idList = "{" . implode(",", $ids) . "}";
$db->prepare("updateImage", "update _elastic_images set is_featured_image=true where ic_id = ANY(\$1)");
$results = $db->execute("updateImage", array($idList));

echo "Done.\n";

