#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
/**
 * Refresh the Elatic Search Indices
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();

$wikiUtil = new \snac\server\util\WikipediaUtil();

$wikiBatchSize = 50;
pg_query($db->getHandle(),"DROP TABLE IF EXISTS _elastic_images");
pg_query($db->getHandle(),"CREATE TABLE _elastic_images (
    ic_id integer not null primary key
    , ark_id text
    , image_url text
    , image_metadata text
);");

echo "Querying relevant ark IDs from the database.\n";
pg_query($db->getHandle(),"insert into _elastic_images (ic_id, ark_id)
    select distinct o.ic_id, replace(n.ark_id,'http://n2t.net/ark:/99166/','') as ark_id
    from otherid o left join _elastic_names n on o.ic_id=n.ic_id where o.uri ilike '%wikidata%'");
pg_query($db->getHandle(),"CREATE INDEX _elastic_images_ndx_1 ON _elastic_images (ark_id)");


echo "Querying wikipedia URLs from the database.\n";
$count = 0;
$db->cursorQuery("wikiURLs","select ic_id, ark_id from _elastic_images");
$updateURLs = $db->prepare("updateWikiURLs","update _elastic_images set image_url=\$2, image_metadata=\$3 where ark_id=\$1");
while ($resource = $db->cursorFetch("wikiURLs",$wikiBatchSize)) {
    if (pg_num_rows($resource) == 0) { break; }
    $ark_ids = array();
    while($row = $db->fetchrow($resource)) {
        $ic_id  = $row["ic_id"];
        $ark_id  = $row["ark_id"];
        if ($ark_id) { $ark_ids[] = $ark_id; }
    }
    $images = $wikiUtil->getWikiImageURLs($ark_ids);
    foreach ($images as $result) {
        $ark_id = $result["_arkID"]["value"];
        $image  = $result["_image"]["value"] ?? null;
        if ($image) {
            $count++;
            if ($count % 10000 == 0) { echo "$count...\n"; }
            $metadata = $wikiUtil->getWikiMetadata($image);
            $db->execute("updateWikiURLs",array($ark_id,$image,json_encode($metadata)));
        }
    }
}
$db->cursorClose("wikiURLs");

echo "Done\n";

