#!/usr/bin/env php
<?php
/**
 * Refresh the Neo4j database
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

use Laudis\Neo4j\Databags\Statement;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();

$batchSize = 10000;


$connector = null;

if (\snac\Config::$USE_NEO4J) {
    $connector = \Laudis\Neo4j\ClientBuilder::create()
        ->withDriver('bolt', \snac\Config::$NEO4J_BOLT_URI)
        ->build();
}

if ($connector == null)
    die("Could not connect to Neo4J");

echo "Querying the names from the database.\n";

$db->cursorQuery("allNames","select one.ic_id, one.version, one.ark_id, two.id as name_id, two.original, two.preference_score, one.entity_type from
    (select
        aa.is_deleted,aa.id,aa.version, aa.ic_id, aa.original, aa.preference_score
    from
        name as aa,
        (select name.id,max(name.version) as version from name
            left join (select v.id as ic_id, v.version, nrd.ark_id
                    from version_history v
                    left join (select bb.id, max(bb.version) as version from
                    (select id, version from version_history where status in ('published', 'deleted', 'tombstone')) bb
                    group by id order by id asc) mv
                    on v.id = mv.id and v.version = mv.version
                    left join nrd on v.id = nrd.ic_id
                    where
                    v.status = 'published'
                    order by v.id asc, v.version desc) vh
                on name.version<=vh.version and
                name.ic_id=vh.ic_id
            group by name.id) as bb
    where
        aa.id = bb.id and
        not aa.is_deleted and
        aa.version = bb.version
    order by ic_id asc, preference_score desc, id asc) two,
    (select v.id as ic_id, v.version, n.ark_id, etv.value as entity_type
    from
        version_history v,
        (select bb.id, max(bb.version) as version from
            (select id, version from version_history where status in ('published', 'deleted', 'tombstone')) bb
            group by id order by id asc) mv,
        vocabulary etv,
        nrd n
    where
        v.id = mv.id and
        v.version = mv.version and
        v.status = 'published' and
        v.id = n.ic_id and
        n.ark_id is not null and
        n.entity_type = etv.id) one
where
    two.ic_id = one.ic_id
order by
    one.ic_id asc, two.preference_score desc, two.id asc;");

$previousICID = -1;
$total = 0;
$count = 0;
while ($resource = $db->cursorFetch("allNames",$batchSize)) {
    if (pg_num_rows($resource) == 0) { break; }
    $stack = array();
    while($name = $db->fetchrow($resource)) {
        $total++;
        if ($previousICID != $name["ic_id"]) {
            $node = [
                "id" => $name["ic_id"],
                "ark" => $name["ark_id"],
                "version" => $name["version"],
                "entity_type" => $name["entity_type"],
                "name" => $name["original"],
                'name_lower' => strtolower($name["original"])
                ];
            $stack[] = new Statement('CREATE (n:Identity) SET n += $infos', [ 'infos' => $node ]);
            $count++;
        }
        $previousICID = $name["ic_id"];
    }
    $txn = $connector->beginTransaction();
    $txn->runStatements($stack);
    $txn->commit();
    $stack = array();
    echo substr("$total      ",0,8)."=> $count nodes...\n";
    pg_free_result($resource);
}
$db->cursorClose("allNames");

$connector->run('CREATE CONSTRAINT IF NOT EXISTS FOR (i:Identity) REQUIRE i.id IS UNIQUE');
$connector->run('CREATE INDEX IF NOT EXISTS FOR (i:Identity) ON (i.name_lower)');


echo "Querying the vocabulary from the database.\n";

$lookup = [ "relation_type" => [] ];
$result = $db->query("select * from vocabulary where type = 'relation_type';", array());
while($row = $db->fetchrow($result))
{
    $lookup["relation_type"][$row["id"]] = [
        "uri" => $row["uri"],
        "value" => $row["value"]
    ];
}


echo "Querying the relations from the database.\n";

$db->cursorQuery("allRel","select r.id, r.version, r.ic_id, cl.current_ic_id as related_id, cl.current_ark_id as related_ark, r.arcrole from
                related_identity r, constellation_lookup cl,
                (select distinct id, max(version) as version from related_identity group by id) a
                where a.id = r.id and a.version = r.version and not r.is_deleted and cl.ic_id = r.related_id");

$count = 0;
while ($resource = $db->cursorFetch("allRel",$batchSize)) {
    if (pg_num_rows($resource) == 0) { break; }
    $stack = array();
    while($row = $db->fetchrow($resource)) {
        $edge = [
            "id" => $row["id"],
            "version" => $row["version"],
            "source" => $row["ic_id"],
            "target" => $row["related_id"],
            "target_ark" => $row["related_ark"],
            "arcrole" => isset($lookup["relation_type"][$row["arcrole"]]) ? $lookup["relation_type"][$row["arcrole"]]["value"] : null
        ];
        $stack[] = new Statement('MATCH (a:Identity {id: $id1 }),(b:Identity {id: $id2 })
            CREATE (a)-[r:ICRELATION $infos]->(b)',
            [
                'id1' => $edge["source"],
                'id2' => $edge["target"],
                'infos' => [
                    "id" => $edge["id"],
                    "version" => $edge["version"],
                    "arcrole" => $edge["arcrole"]
                ]
            ]);
        $count++;
    }
    $txn = $connector->beginTransaction();
    $txn->runStatements($stack);
    $txn->commit();
    $stack = array();
    echo "Committed $count edges...\n";
    pg_free_result($resource);
}
$db->cursorClose("allRel");
