#!/usr/bin/env php
<?php
/**
 * Refresh the Neo4j database
 *
 * This script is more "dirty" to be efficient in rebuilding the Elastic Search index.  It queries
 * the postgres database directly to get required information to build the elastic search indices.
 *
 * It fills two indices by default: the base search index for UI interaction and the all names index
 * for identity reconciliation.
 *
 * @author Robbie Hott
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 * @copyright 2015 the Rector and Visitors of the University of Virginia, and
 *            the Regents of the University of California
 */
// Include the global autoloader generated by composer
include "../../vendor/autoload.php";

use \Monolog\Logger;
use \Monolog\Handler\StreamHandler;

use \Laudis\Neo4j\Databags\Statement;

// Set up the global log stream
$log = new StreamHandler(\snac\Config::$LOG_DIR . \snac\Config::$SERVER_LOGFILE, Logger::DEBUG);

// SNAC Postgres DB Connector
$db = new \snac\server\database\DatabaseConnector();

$batchSize = 2000;

$connector = null;

if (\snac\Config::$USE_NEO4J) {
    $connector = \Laudis\Neo4j\ClientBuilder::create()
        ->withDriver('bolt', \snac\Config::$NEO4J_BOLT_URI)
        ->build();
}

if ($connector == null)
    die("Could not connect to Neo4J");

echo "Querying the resources from the database.\n";

$db->cursorQuery("allNames","select b.id, cl.current_ic_id as repo_ic_id
                        from resource_cache b, constellation_lookup cl,
                        (select distinct id, max(version) as version from resource_cache group by id) a
                        where b.id = a.id and b.version = a.version and not b.is_deleted and b.repo_ic_id is not null and b.repo_ic_id = cl.ic_id");
$count = 0;
while ($resource = $db->cursorFetch("allNames",$batchSize)) {
    if (pg_num_rows($resource) == 0) { break; }
    $stack = array();
    while($name = $db->fetchrow($resource)) {
        $count++;
        if ($name["repo_ic_id"] == null) { continue; }
        $stack[] = new Statement('MATCH (a:Identity {id: $id1 }),(b:Resource {id: $id2 })
            CREATE (b)-[r:HIRELATION]->(a);',
            [
                'id1' => $name["repo_ic_id"],
                'id2' => $name["id"]
        ]);
    }
    $txn = $connector->beginTransaction();
    $result = $txn->runStatements($stack);
    $txn->commit();
    $stack = array();
    echo "Committed $count edges\n";
    pg_free_result($resource);
}
$db->cursorClose("allNames");
