name: Test WorkFlow

on:
  push:
    branches-ignore:
      - development
      - master
      - jnm/github-actions

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, bcmath, csv
      - name: Setup code
        run: |
          composer config github-oauth.github.com ${{ secrets.COMPOSER_ACCESS_TOKEN }}
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
          echo $CONFIG_FILE | base64 --decode > src/snac/Config.php
          echo $USER_LIST >> install/setup_files/users.csv
          mkdir -p coverage/
      - name: Setup database
        run: |
          cd install && php install.php automate
          cd ..
          tar xzvf test/testing.sql.tar.gz
          cd scripts && php refresh.php automate ../test/testing.sql
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_PORT: 5432
        run: vendor/bin/phpunit --coverage-text --colors=never
