name: Test WorkFlow

on:
  push:
    branches-ignore:
      - development
      - master
      - jnm/github-actions

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, bcmath, csv
      - name: Setup code
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          cp ~/Config.php src/snac/Config.php
          cp ~/users.csv install/setup_files/users.csv
          rm -rf ~/public_html/snac_server
          ln -s `pwd`/src/virtualhosts ~/public_html/snac_server
          ln -s `pwd`/src/snac/client/webui/templates ~/webui_templates
          ln -s `pwd`/src/snac/client/webui/languages ~/webui_languages
          ln -s `pwd`/src/snac/util ~/cpf_templates
          mkdir -p coverage/
      - name: Setup database
        run: |
          cd install && php install.php automate
          cd ..
          cd scripts && php refresh.php automate /home/gitlab-runner/testing.sql
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_PORT: 5432
        run: vendor/bin/phpunit --coverage-text --colors=never
